#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

server:
  servlet:
    context-path: /

### xxl-job, datasource
spring:
  datasource:
    url: jdbc:mysql://172.31.6.136:2116/xxl_job?useUnicode=true&amp;characterEncoding=UTF8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true&amp;zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: rede
    password: 1qaz2wsx

xxl:
  job:
    accessToken: jerery816
    i18n:
