#日志路径
log:
  file:
    path: /data/java_service/logs2/@profile-active@
    max-size: 128MB
    max-history: 180

### xxl-job, datasource
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/xxl_job2.1?useUnicode=true&amp;characterEncoding=UTF8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true&amp;zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: rede
    password: RedE2019!!

### 外网登录账号 admin 密码rede@admin
xxl:
  job:
    accessToken: a02d4b20ab655ec85277c86e
    i18n:
