#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

### 调度中心JDBC链接：链接地址请保持和所创建的调度数据库的地址一致
spring:
  datasource:
    url: jdbc:mysql://47.102.126.144:3306/xxl_job?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1qaz2wsx

xxl:
  job:
    ### 调度中心通讯TOKEN [选填]：非空时启用；
    accessToken: gfdsgfdssgsdfdfsdfsd
    ### 调度中心国际化配置 [选填]： 默认为空，表示中文; "en" 表示英文；
    i18n:
