#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 64MB
    max-history: 7

jasypt:
  encryptor:
    property:
      prefix: RedE(   # 加密前缀
      suffix: )            # 加密后缀
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

### xxl-job, datasource
spring:
  datasource:
    url: RedE(sD6V2f0i2KeugR1SaXPqKDL252IE2gUxDcM9VBBtsCddyh79ZTBDCiwH6qICo7uJ580sw7gN51pvWrGch2cKZcCPqXlc5PwnsDrH57rH4YasNtmiiBGH7EAqNjInTBcRgZFAYMHaR2kflM+50gRKt/zD3/P7uAvPWVXGWLe0623djM1xWLyXJigp4K+ISuhF0lDXCClGZ4BiUxVFUckg1OgSWg4IwNVCFu3Vl6z3sacpymjc8/eOPrWc4qkiqBmplPzY/5djCCiZUedMdYDNHLalBwh5AkCuf9CWEeuN0PpXWPt2jKXfgufgHersdTjI+y0plVK9e6bAONWNquDD6StrVp8FjNJCE0mw8B2WGcpELH2IeWExujMDsAdiPQIx)
    driver-class-name: com.mysql.jdbc.Driver
    username: RedE(b/cPqWCjHF4m2Bu5ienqRQ==)
    password: RedE(s2/KOaAY6bZrXWMkF0x9kr+P1W3TxOxHms3rrY5DNSLICvTG0nBbUPyXIieMfnnR)

### 外网登录账号 admin 密码rede@admin
xxl:
  job:
    accessToken: a02d4b20ab655ec85277c86e
    i18n:
