#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://172.31.3.48:2181?backup=172.31.3.48:2182,172.31.3.48:2183

# swagger配置

jasypt:
  encryptor:
    property:
      prefix: RedE(   # 加密前缀
      suffix: )            # 加密后缀
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

spring:
  #上传配置
  http:
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 20MB
      enabled: true
  #数据库连接
  datasource:
    url: RedE(nxCMVOLkKHv+MLsgcjvb/krHjznklQHK2vJg7bj8nfQNsN01adBSnFibaA0o7kTMymx/1sfnpejgOevunVPGx5xcS9E+6yjjDzQnC4yK8rss22Z0j84c0gjHEqoHyK0IOXdnwMr1bMjKt4IhglIvsJB59piqPwJ2a7wUhCT8aqpGhwBGzqBgfG1eU1UCE+n4jXUgZAU4Vu8kW24JTy+HyUq0GPnYNS3Zm1uJVL9jymtsNc8XxpAAwgh+seKiOoft+rmLTW5uYtd+nwv2wMxok7p17m9zm87lN9hjaunuf+x6TJVHaaz8T30yE0ychPQa/E0/TkKJOQ0p6pWNOgQX8Q==)
    username: RedE(2mrIxb+xr0JIkJZhpZM6rw==)
    password: RedE(9xt4+dxZg7UJ2xBU2RxnIWPv/HPPdya2mAko1SSIglQLFWER6wFnCDrF700p4xLB)
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      # 监控页面的用户名和密码 以及页面地址
      stat-view-servlet:
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.3.48:7000
        - 172.31.3.48:7001
        - 172.31.3.48:7002
        - 172.31.3.48:7003
        - 172.31.3.48:7004
        - 172.31.3.48:7005        
  # swagger在线文档配置
  swagger:
    enabled: false                                       # 是否启用swagger
 

oss:                                                                                                                    #阿里oss上传
  #oss 使用http、https请求方式
  protocol: HTTPS



# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.d.xqcx.com:32181?backup=zk2.d.xqcx.com:32181,zk3.d.xqcx.com:32181

