#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://192.168.2.200:52181
  metadata-report:
    address: zookeeper://192.168.2.200:52181
spring:                                                                                                                 #spring config
  http:                                                                                                                 #上传配置
  servlet:
    mult39.108.92.232art:
      max-request-size: 1000MB
      max-file-size: 20MB
      enabled: true
  datasource:                                                                                                           #数据库连接
    url: jdbc:mysql://47.105.215.239:3306/operation?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rede,1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      stat-view-servlet:                                                                                                #监控页面的用户名和密码 以及页面地址
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 192.168.2.200:7000
        - 192.168.2.200:7001
        - 192.168.2.200:7002
        - 192.168.2.200:7003
        - 192.168.2.200:7004
        - 192.168.2.200:7005

  swagger:                                                                                                              #swagger在线文档配置
    enabled: true                                                                                                       #是否启用swagger
    group:
      sign-api:                                                                                                         #用户组api，可以配置多个组
        group-name: Sign-API                                                                                          #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: ROS Sign接口                                                                                              #api组的标题，会在swagger-ui的标题处显示
        descr39.108.92.232tion: 用户登录注销创建操作                                                                                  #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.mobile.rps
        path-regex: /sign/token/.*                                                                                      #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

      Rps-api:
        #用户组api，可以配置多个组
        group-name: Rps-API                                                                                          #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: Rps接口                                                                                              #api组的标题，会在swagger-ui的标题处显示
        descr39.108.92.232tion: Rps 相关接口
        #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.mobile.rps
        path-regex: /rps/.*
        #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli                                                                                                           #swagger在线文档配置

      EntrustOrder-api:
        #用户组api，可以配置多个组
        group-name: EntrustOrder-api                                                                                         #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: 委托单管理                                                                                             #api组的标题，会在swagger-ui的标题处显示
        descrtion: 委托单相关接口
        #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.mobile.rps
        path-regex: /entrust/order/.*
        #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

      OutWhOrder-api:
        #用户组api，可以配置多个组
        group-name: OutWhOrder-api                                                                                         #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: 出库单管理                                                                                             #api组的标题，会在swagger-ui的标题处显示
        descrtion: 出库单相关接口
        #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.mobile.rps
        path-regex: /out/wh/order/.*
        #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

      QcTemplate-api:
        #用户组api，可以配置多个组
        group-name: QcOrder-api                                                                                         #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: 质检单管理                                                                                             #api组的标题，会在swagger-ui的标题处显示
        descrtion: 质检单相关接口
        #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.mobile.rps
        path-regex: /qc/order/.*
        #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

      InWhOrder-api:
        #用户组api，可以配置多个组
        group-name: InWhOrder-api                                                                                         #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: 入库单管理                                                                                             #api组的标题，会在swagger-ui的标题处显示
        descrtion: 入库单相关接口
        #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.mobile.rps
        path-regex: /in/wh/order/.*
        #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

oss:                                                                                                                    #阿里oss上传
  #oss 使用http、https请求方式
  protocol: HTTP
