#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
dubbo:
  registry:
    address: zookeeper://10.1.1.142:2181?backup=10.1.1.142:2182,10.1.1.142:2183
  metadata-report:
    address: zookeeper://10.1.1.142:2181?backup=10.1.1.142:2182,10.1.1.142:2183
spring:
  #上传配置
  http:
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 20MB
      enabled: true
  datasource:
    url: jdbc:mysql://10.1.2.53:2021/operation_prod?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: rede
    password: rede1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      # 监控页面的用户名和密码 以及页面地址
      stat-view-servlet:
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 10.1.2.53:7000
        - 10.1.2.53:7001
        - 10.1.2.53:7002
        - 10.1.2.53:7003
        - 10.1.2.53:7004
        - 10.1.2.53:7005
  # swagger在线文档配置
  swagger:
    enabled: false                                       # 是否启用swagger
 

oss:                                                                                                                    #阿里oss上传
  #oss 使用http、https请求方式
  protocol: HTTPS