#日志路径
log:
  file:
    path: /data/java_service/logs/@profile-active@
    max-size: 128MB
    max-history: 180

## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://10.211.55.5:12181?backup=10.211.55.5:22181,10.211.55.5:32181
  metadata-report:
    address: zookeeper://10.211.55.5:12181?backup=10.211.55.5:22181,10.211.55.5:32181
  config-center:
    address: zookeeper://10.211.55.5:12181?backup=10.211.55.5:22181,10.211.55.5:32181

spring:
  datasource:
    dynamic:
      # 配置默认数据源
      primary: corporate
      datasource:
        corporate:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/corporate?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
          username: root
          password: 1qaz2wsx
        operation:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/operation?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
          username: root
          password: 1qaz2wsx
        consumer:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/consumer?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
          username: root
          password: 1qaz2wsx
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 10.211.55.5:7000
        - 10.211.55.5:7001
        - 10.211.55.5:7002
        - 10.211.55.5:7003
        - 10.211.55.5:7004
        - 10.211.55.5:7005



