#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://192.168.2.211:2181
  metadata-report:
    address: zookeeper://192.168.2.211:2181
spring:
  datasource:
    dynamic:
      # 配置默认数据源
      primary: corporate
      seata: true
      datasource:
        corporate:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.2.211:3306/corporate?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
          username: dev
          password: 1qaz2wsx
        operation:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.2.211:3306/operation?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
          username: dev
          password: 1qaz2wsx
        consumer:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.2.211:3306/consumer?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
          username: dev
          password: 1qaz2wsx
        website:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://192.168.2.211:3306/website?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
          username: dev
          password: 1qaz2wsx
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 192.168.2.211:7000
        - 192.168.2.211:7001
        - 192.168.2.211:7002
        - 192.168.2.211:7003
        - 192.168.2.211:7004
        - 192.168.2.211:7005


# 多注册中心配置
#    reg2:
#      group: corporte
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys


seata:
  enabled: true
  enable-auto-data-source-proxy: false
  tx-service-group: ses-service-hub-group
  registry:
    type: zk
    zk:
      server-addr: 192.168.2.211:2181
      cluster: default
      connect-timeout: 2000000
  config:
    type: zk
    zk:
      server-addr: 192.168.2.211:2181
      connect-timeout: 2000000
  service:
    disable-global-transaction: false
    vgroup-mapping:
      ses-service-hub-group: default
  client:
    rm:
      report-success-enable: false