#日志路径
log:
  file:
    path: /data/java_service/logs/@profile-active@
    max-size: 128MB
    max-history: 180

# DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://172.16.0.205:12181?backup=172.16.0.205:22181,172.16.0.205:32181

spring:
  datasource:
    dynamic:
      # 配置默认数据源
      primary: corporate
      datasource:
        corporate:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.16.0.205:3306/corporate?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
          username: root
          password: 1qaz2wsx
        operation:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.16.0.205:3306/operation?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
          username: root
          password: 1qaz2wsx
        consumer:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.16.0.205:3306/consumer?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
          username: root
          password: 1qaz2wsx
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.16.0.205:7000
        - 172.16.0.205:7001
        - 172.16.0.205:7002
        - 172.16.0.205:7003
        - 172.16.0.205:7004
        - 172.16.0.205:7005


# 多注册中心配置
#    reg2:
#      group: corporte
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys
