#日志路径
log:
  file:
    path: logs/local
    max-size: 128MB
    max-history: 180
#spring config
spring:
  http:                                                                                                                 #上传配置
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 20MB
      enabled: true
  datasource:                                                                                                           #数据库连接
    url: jdbc:mysql://localhost:3306/operation?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
    username: root
    password: 1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      stat-view-servlet:                                                                                                #监控页面的用户名和密码 以及页面地址
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  swagger:                                                                                                              #swagger在线文档配置
    enabled: true                                                                                                       #是否启用swagger
    group:
      all-api:                                                                                                          #用户组api，可以配置多个组
        group-name: Admin Dev RESTful API                                                                               #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: Admin Dev Online Documentation                                                                           #api组的标题，会在swagger-ui的标题处显示
        description: Admin Dev Management System                                                                        #api组的描述，会在swagger-ui的描述中显示
        path-regex: /.*                                                                                                 #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.0                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli                                                                             #联系地址

redis:                                                                                                                  #REDIS配置
  redis-address: localhost:7000;localhost:7001;localhost:7002;localhost:7003;localhost:7004;localhost:7005


dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://localhost:12181
