#Springboot 基础配置
spring:
  application:
    name: ses-admin-dev
  profiles:
    active: local
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
    encoding: UTF-8
  #数据库连接
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  #编码格式
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
server:
  port: 18090
  servlet:
    context-path: /ses/admin/dev/api
  tomcat:
    uri-encoding: UTF-8
# Spring boot actuator 配置
management:
  server:
    servlet:
      context-path: "/management"
    port: 28088
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/monitor"
  endpoint:
    shutdown:
      enabled: true

#REDIS配置
redis:
  max-total: 10000
  max-idle: 200
  min-Idle: 50
  timeout: 3000
  max-attempts: 5
#MYBATIS配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#mybaits-plus配置，此配置 不影响原始的mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/base/*Mapper.xml,classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.redescooter.ses.app.crm.web.vo, com.redescooter.ses.app.crm.web.vo.base
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #配置逻辑删除字段为1是删除
    logic-delete-value: 1
    #配置逻辑删除字段为0是未删除
    logic-not-delete-value: 0
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

# DUBBO 配置
dubbo:
  application:
    id: ses-admin-dev
    name: ses-admin-dev
    qos-enable: false
    qos-accept-foreign-ip: true
    version: 1.0.0
  scan:
    base-packages: com.redescooter.ses  #服务暴露与发现消费所在的package
  registry:
    address: zookeeper://39.108.92.232:22181
    check: false
    timeout: 30000
  metadata-report:
    address: zookeeper://39.108.92.232:22181
    timeout: 30000
  protocol:
    name: dubbo
    port: 20888
    threads: 300
  provider:
    .
    validation: true
    timeout: 30000
    group: ses
  consumer:
    check: false
    timeout: 20000
    filter: DubboAccessLogFilter
