#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://192.168.2.200:2181
spring:                                                                                                                 #spring config
  http:                                                                                                                 #上传配置
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 20MB
      enabled: true
  datasource:                                                                                                           #数据库连接
    url: jdbc:mysql://192.168.2.200:3306/corporate?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      stat-view-servlet:                                                                                                #监控页面的用户名和密码 以及页面地址
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 192.168.2.200:7000
        - 192.168.2.200:7001
        - 192.168.2.200:7002
        - 192.168.2.200:7003
        - 192.168.2.200:7004
        - 192.168.2.200:7005

  swagger:                                                                                                              #swagger在线文档配置
    enabled: true                                                                                                       #是否启用swagger
    group:
      sign-api:                                                                                                         #用户组api，可以配置多个组
        group-name: 登录注销                                                                                          #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: SaaS Sign API                                                                                          #api组的标题，会在swagger-ui的标题处显示
        description: 用户登录注销创建操作                                                                                  #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.web.delivery
        path-regex: /sign/token/.*                                                                                      #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli                                                                             #联系地址                                                                         #联系地址

      driver-api:                                                                                                         #用户组api，可以配置多个组
        group-name: 快递司机                                                                                        #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: Driver API                                                                                              #api组的标题，会在swagger-ui的标题处显示
        description: 快递司机                                                                                  #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.web.delivery
        path-regex: /ed/driver/.*                                                                                      #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli                                                                             #联系地址

      fleet-api:                                                                                                         #用户组api，可以配置多个组
        group-name: 快递车辆                                                                                          #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: Scooter API                                                                                            #api组的标题，会在swagger-ui的标题处显示
        description: 快递车辆                                                                                  #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.web.delivery
        path-regex: /ed/scooter/.*                                                                                      #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

      Order-api:                                                                                                         #用户组api，可以配置多个组
        group-name: 快递订单                                                                                         #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: ED Order API                                                                                            #api组的标题，会在swagger-ui的标题处显示
        description: 快递订单                                                                                  #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.web.delivery
        path-regex: /ed/orders/.*                                                                                      #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

      Task-api:                                                                                                         #用户组api，可以配置多个组
        group-name: 快递任务                                                                                        #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: ED Task API                                                                                            #api组的标题，会在swagger-ui的标题处显示
        description: 快递任务                                                                                  #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.web.delivery
        path-regex: /ed/task/.*                                                                                      #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

      Dashboard-api:                                                                                                         #用户组api，可以配置多个组
        group-name: 快递仪表盘                                                                                        #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: ED Task API                                                                                            #api组的标题，会在swagger-ui的标题处显示
        description: 快递仪表盘                                                                                  #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.web.delivery
        path-regex: /ed/dashboard/.*                                                                                      #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

      CommonSet-api:                                                                                                         #用户组api，可以配置多个组
        group-name: 公共配置服务                                                                                        #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: CommonSet Common API                                                                                            #api组的标题，会在swagger-ui的标题处显示
        description: CommonSet                                                                                  #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.web.delivery
        path-regex: /common/setting/.*                                                                                      #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

      CommonMaggess-api:                                                                                                         #用户组api，可以配置多个组
        group-name: 公共消息服务                                                                                        #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: CommonMaggess Common API                                                                                            #api组的标题，会在swagger-ui的标题处显示
        description: CommonMaggess                                                                                  #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.web.delivery
        path-regex: /common/message/.*                                                                                      #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli                                                                         #联系地址

      EDAddress-api:                                                                                                       #用户组api，可以配置多个组
        group-name: EDAddress管理API                                                                                   #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: EDAddress API                                                                                            #api组的标题，会在swagger-ui的标题处显示
        description: EDAddress管理API                                                                                  #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses.web.delivery
        path-regex: /ed/address/.*                                                                                      #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.1                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli

oss:                                                                                                                    #阿里oss上传
  #oss 使用http、https请求方式
  protocol: HTTP


seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: ses-web-delivery-group
  registry:
    type: zk
    zk:
      server-addr: 192.168.2.200:2181
      cluster: default
      connect-timeout: 2000000
  config:
    type: zk
    zk:
      server-addr: 192.168.2.200:2181
      connect-timeout: 2000000
  service:
    disable-global-transaction: false
    vgroup-mapping:
      ses-web-delivery-group: default
  client:
    rm:
      report-success-enable: false