#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://172.31.3.48:2181?backup=172.31.3.48:2182,172.31.3.48:2183

# swagger配置

jasypt:
  encryptor:
    property:
      prefix: RedE(   # 加密前缀
      suffix: )            # 加密后缀
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

spring:
  #上传配置
  http:
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 20MB
      enabled: true
  #数据库连接
  datasource:
    url: RedE(F1Q2JN3cQrlrbfQsZsj48j8q2QftYwq/Xz2jpAEShI1UMVWQNRQeBV0dEicdNSa9cejE53tG9edqpIE7XdMwRFF5rdG5W1ViPMKG/ubOdOE4XdENUGyjvp5XM7MEwUw5yQxKASdO2onhTg6MygCRRfodbln5j9QmVrpfcwMio79mITlfvMmpP/zBUa4fSdAEmU99s0odFwvJoYBsPQmyIbPbit1ZpNwzWpRGnrab1YAUaf4D4vhpVSnEV9MfOAAyTUdNq3x0oRx5z1s7sLtBwTJD3HQqzO5dfGxnhfheXOxV+0qoUOrIMc9VZg965DQQ0A8ZIPT3y8bN8GoqEES1QQ==)
    username: RedE(NqQr1ppQnSUFwW3C88oKrA==)
    password: RedE(bH6R75pS0stRNmMwnN8eMS5papPsmLksEPyTlJkaMvKYy3mnEzxS6mOtAQfBt/oh)
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      # 监控页面的用户名和密码 以及页面地址
      stat-view-servlet:
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.3.48:7000
        - 172.31.3.48:7001
        - 172.31.3.48:7002
        - 172.31.3.48:7003
        - 172.31.3.48:7004
        - 172.31.3.48:7005
  # swagger在线文档配置
  swagger:
    enabled: false                                       # 是否启用swagger

oss:                                                                                                                    #阿里oss上传
  #oss 使用http、https请求方式
  protocol: HTTPS



# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.d.xqcx.com:32181?backup=zk2.d.xqcx.com:32181,zk3.d.xqcx.com:32181

