log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
dubbo:
  registry:
    address: zookeeper://172.28.193.226:2181
  metadata-report:
    address: zookeeper://172.28.193.226:2181
spring:
  datasource:
    url: jdbc:mysql://172.28.193.226:3306/scooter?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rede,1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  redis:
    cluster:
      nodes:
        - 172.28.193.226:7000
        - 172.28.193.226:7001
        - 172.28.193.226:7002
        - 172.28.193.226:7003
        - 172.28.193.226:7004
        - 172.28.193.226:7005
mqtt:
  ca: /root/certs/test/my_root_ca.pem
  clientCrt: /root/certs/test/client.pem
  clientKey: /root/certs/test/client.key
  timeout: 60
  keepalive: 60
  url: ssl://iclient.redescooter.net



seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: ses-service-scooter-group
  registry:
    type: zk
    zk:
      server-addr: 172.28.193.226:2181
      cluster: default
      connect-timeout: 2000000
  config:
    type: zk
    zk:
      server-addr: 172.28.193.226:2181
      connect-timeout: 2000000
  service:
    disable-global-transaction: false
    vgroup-mapping:
      ses-service-scooter-group: default
  client:
    rm:
      report-success-enable: false
