#日志路径
log:
  file:
    path: /data/java_service/logs2/@profile-active@
    max-size: 128MB
    max-history: 180

spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scooter_prod924?useUnicode=true&amp;characterEncoding=UTF8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true&amp;zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
    username: rede
    password: RedE2019!!
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000

#REDIS配置
redis:
  redis-address: 127.0.0.1:7000;127.0.0.1:7001;127.0.0.1:7002;127.0.0.1:7003;127.0.0.1:7004;127.0.0.1:7005

# DUBBO 配置
dubbo:
  registries:
    ses:
      group: ses
      address: zookeeper://127.0.0.1:32181
# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys

#35.180.46.199:7332;35.180.46.199:7332 环境2：13.209.4.155:7332
iot:
  address: 106.14.206.178:7332
