#日志路径
log:
  file:
    path: logs/@profile-active@
    max-size: 128MB
    max-history: 180

spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://39.108.92.232:3306/scooter_test?useUnicode=true&amp;characterEncoding=UTF8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true&amp;zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
    username: root
    password: 1qaz2wsx
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000

#REDIS配置
redis:
  redis-address: 39.108.92.232:7000;39.108.92.232:7001;39.108.92.232:7002;39.108.92.232:7003;39.108.92.232:7004;39.108.92.232:7005

# DUBBO 配置
dubbo:
  registries:
    ses:
      group: ses
      address: zookeeper://39.108.92.232:22181
# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:2181?backup=zk2.t.xqcx.com:2181,zk3.t.xqcx.com:2181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:2181,zk2.t.xqcx.com:2181,zk3.t.xqcx.com:2181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys

#35.180.46.199:7332;35.180.46.199:7332
iot:
  address: 106.14.206.178:7332

