#日志路径
log:
  file:
    path: logs/@profile-active@
    max-size: 128MB
    max-history: 180

spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://localhost:3306/scooter?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 10.211.55.5:7000
        - 10.211.55.5:7001
        - 10.211.55.5:7002
        - 10.211.55.5:7003
        - 10.211.55.5:7004
        - 10.211.55.5:7005

# DUBBO 配置
dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://10.211.55.5:12181?backup=10.211.55.5:22181,10.211.55.5:32181


# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:2181?backup=zk2.t.xqcx.com:2181,zk3.t.xqcx.com:2181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:2181,zk2.t.xqcx.com:2181,zk3.t.xqcx.com:2181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys

#35.180.46.199:7332;35.180.46.199:7332
iot:
  address: 106.14.206.178:7332

