log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
dubbo:
  registry:
    address: zookeeper://172.31.8.126:2181
  metadata-report:
    address: zookeeper://172.31.8.126:2181
spring:
  datasource:
    url: jdbc:mysql://172.31.8.126:3306/scooter?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rede,1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  redis:
    cluster:
      nodes:
        - 172.31.8.126:7000
        - 172.31.8.126:7001
        - 172.31.8.126:7002
        - 172.31.8.126:7003
        - 172.31.8.126:7004
        - 172.31.8.126:7005
mqtt:
  ca: /root/certs/my_root_ca.pem
  clientCrt: /root/certs/client.pem
  clientKey: /root/certs/client.key
  timeout: 60
  keepalive: 60
  url: ssl://client.redemotors.com
