log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
dubbo:
  registry:
    address: zookeeper://172.31.6.101:2181
  metadata-report:
    address: zookeeper://172.31.6.101:2181
spring:
  http:
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 100MB
      enabled: true
  datasource:
    url: jdbc:mysql://172.31.6.136:2116/admin_dev_pre?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: redpre
    password: pre.1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      stat-view-servlet:
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  redis:
    cluster:
      nodes:
        - 172.31.6.136:7000
        - 172.31.6.136:7001
        - 172.31.6.136:7002
        - 172.31.6.136:7003
        - 172.31.6.136:7004
        - 172.31.6.136:7005
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    default-requeue-rejected: false
    publisher-confirms: true
    listener:
      simple:
        acknowledge-mode: MANUAL
  swagger:
    enabled: true
    group:
      sign-api:
        group-name: 1.Login-API
        title: OMS Login相关接口
        description: 登陆相关接口
        base-package: com.redescooter.ses
        path-regex: /admin/dev.*
        path-mapping: /
        version: v1.2.1
        license: RedE 公司内部传阅
        license-url: '#'
        terms-of-service-url:
        contact:
          name: 李加廷
          email: jerry@redescooter.com
          url: https://github.com/mrjerryli

#应用更新包文件上传下载路径
fileUpload:
  path: /opt/nginx/soft/download/
  download: https://pre.redelectric.fr/ses/t/admin/w/dev/api/app/version/downLoadFile/


seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: ses-admin-dev-group
  registry:
    type: zk
    zk:
      server-addr: 172.31.6.101:2181
      cluster: default
      connect-timeout: 2000000
  config:
    type: zk
    zk:
      server-addr: 172.31.6.101:2181
      connect-timeout: 2000000
  service:
    disable-global-transaction: false
    vgroup-mapping:
      ses-admin-dev-group: default
  client:
    rm:
      report-success-enable: false
