log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
dubbo:
  registry:
    address: zookeeper://192.168.2.211:2181
  metadata-report:
    address: zookeeper://192.168.2.211:2181
spring:
  http:
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 100MB
      enabled: true
  datasource:
    url: jdbc:mysql://192.168.2.211:3306/admin-dev?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: dev
    password: 1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      stat-view-servlet:
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  redis:
    cluster:
      nodes:
        - 192.168.2.211:7000
        - 192.168.2.211:7001
        - 192.168.2.211:7002
        - 192.168.2.211:7003
        - 192.168.2.211:7004
        - 192.168.2.211:7005

  swagger:
    enabled: true
    group:
      sign-api:
        group-name: 1.Login-API
        title: OMS Login相关接口
        description: 登陆相关接口
        base-package: com.redescooter.ses
        path-regex: /admin/dev.*
        path-mapping: /
        version: v1.2.1
        license: RedE 公司内部传阅
        license-url: '#'
        terms-of-service-url:
        contact:
          name: 李加廷
          email: jerry@redescooter.com
          url: https://github.com/mrjerryli
      AppVersion-api:
        group-name: 2.AppVersion-API
        title: 应用版本管理
        description: 应用版本管理
        base-package: com.redescooter.ses
        path-regex: /app/version/.*
        path-mapping: /
        version: v1.2.1
        license: RedE 公司内部传阅
        license-url: '#'
        terms-of-service-url:
        contact:
          name: 李加廷
          email: jerry@redescooter.com
          url: https://github.com/mrjerryli
      DataCount-api:
        group-name: 3.DataCount-API
        title: 首页dashboard统计
        description: 首页dashboard统计
        base-package: com.redescooter.ses
        path-regex: /data/count/.*
        path-mapping: /
        version: v1.2.1
        license: RedE 公司内部传阅
        license-url: '#'
        terms-of-service-url:
        contact: #文档联系人
          name: 李加廷
          email: jerry@redescooter.com
          url: https://github.com/mrjerryli
      scooter-api:
        group-name: 3.Scooter-API
        title: 车辆管理
        description: 车辆管理
        base-package: com.redescooter.ses
        path-regex: /scooter/.*
        path-mapping: /
        version: v1.2.1
        license: RedE 公司内部传阅
        license-url: '#'
        terms-of-service-url:
        contact:
          name: 李加廷
          email: jerry@redescooter.com
          url: https://github.com/mrjerryli
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    default-requeue-rejected: false
    publisher-confirms: true
    listener:
      simple:
        acknowledge-mode: MANUAL

# 应用更新包文件上传下载路径
fileUpload:
    path: /usr/local/nginx/soft/download/
    download: http://192.168.2.211/download/
