server:
  port: 6666
  servlet:
    context-path: /ses/t/admin/w/dev/api
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
  shutdown: graceful
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @profile-active@
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
    encoding: UTF-8
  datasource:                                                                                                           #数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      filters: stat,wall
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  redis:
    cluster:
      max-redirects: 3
    timeout: 6000
    jedis:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 200
        min-idle: 50
  freemarker:
    check-template-location: false
management:
  server:
    port: 1111
    base-path: "/management"
  endpoints:
    enabled-by-default: true
    web:
      base-path: "/monitor"
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
dubbo:
  application:
    id: @project.artifactId@
    name: @project.artifactId@
    qos-enable: false
    qos-accept-foreign-ip: false
    logger: log4j
  scan:
    base-packages: com.redescooter.ses
  registry:
    simplified: true
    check: false
    register: true
    subscribe: true
    dynamic: true
    group: ses
    protocol: zookeeper
    timeout: 60000
    session: 60000
  metadata-report:
    group: ses
    cycle-report: true
    timeout: 60000
  consumer:
    check: false
    lazy: true
    timeout: 60000
    threads: 600
    filter: dubboAccessLogFilter
  protocol:
    register: true
    port: -1
    threads: 400
    name: dubbo
  reference:
    check: false
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.redescooter.ses.admin.dev.vo，com.redescooter.ses.admin.dev.vo.dm
  global-config:
    banner: true
    db-config:
      id-type: uuid
      logic-delete-field: dr
      logic-delete-value: 1
      logic-not-delete-value: 0
      table-underline: true
      capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    aggressive-lazy-loading: true
    lazy-loading-enabled: true
    auto-mapping-unknown-column-behavior: warning
    local-cache-scope: session
    call-setters-on-nulls: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
oss:
  internalEndpoint: oss-cn-shanghai.aliyuncs.com
  accessKeyId: LTAIDUpZRjkFVCze
  secretAccesskey: lVM6XOqSdrdgJ3brHRcdSUOAVdxcS5
  defaultBucketName: rede
  publicEndpointDomain: oss-cn-shanghai.aliyuncs.com
  maxFileSize: 104857600
Request:
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCchHDOG0HP2oE6neIA0Q4Y0BDdbzNCDJdfCk+GxKA/ma2xEya4huuIQ9xKjO0e0E3CqKrCdrc5mOZqfjI2vg0LiDzHmGfRG3JmmHGXocNJlG/EoQerWQqSAN3GsfHnxWiGamHSLbq2+YcBrHxS93z8nOqAEG0u6IHooiNPdVmKasMzPIr4hU7BcYKvZ88485qQBG5ySu4xggg2h6WJy7lphEjRO8qpZlUqvMcnpu+qzELcaV1vEcCPUhPBzUbCbOupdzbBvD/ebzdnjXvoX4NrtC6vmRD+xCSpNLxnP0OOy8T7erv6W7WfXcB9pvukRSBay2zNWDKCDPUQa0/aZTHXAgMBAAECggEAZrmR4+QF1KqfaF5ZB5otu2FLwFmMdcwXyTvWKCiC2Fs/oVllb3S1v1Byk8dclX23m4vhzxHlfXr5t2kuAbnIjAoVghZoBNkTw3xICXIU3wT6Oj5J707YXi0NYaxGjYyF5rqJi02SHyc0UYfobPeb45wFWJnvXvsg0BMiQ7NMWkhjJSRzm1dw2unKcIoEG28azWvoI6ItRGzMBGIIDgAG2nIoTmLI1NakEa72GvPSk1n5ec2iCz9WEl+O+p11Oj+y9VC89nc802ilUpdBupHR4HzNOg0lFv7FxkxHgjVIY9iejxSVvfZobu/kchbAOsxtsn0iYT9BQkw5TdzwrxDRQQKBgQDJCKJUl5LbX5+CvJ9meUAbd1dEGwoVrwspHAeCdDykgNvoHd+g64OYhZ6GHSN8+biXTBI4cghTjOns/SLS728JiRd99VVl0OsQ2VgYq0ju0ATHkAGUIryKgYnMFNNYc+BsZESx4kC7IEHWJg/jnFkP6ltEUxETbvdFJVxPoxp3NwKBgQDHT+FWKvuabdU6vj6coITdE43CzVIvAH82kAEjJkVRO3m0wMrc+SBBDN+w8HUYaNT7aDUgI3Vq1TMz/2+oGYB31EcFTNygxRffhUugkNxk5ceXmc0wYSPZqj3T3TE/v9KdR+jxOw8LAqnKG6AytAFeSaz/P37CviIlfMKsUikqYQKBgQCX2k3EWDo2OyTiPFirrysdlCf26fXUK0Ti6KlDgUnNeQijbO1fQIdGzqfP5nLIFFm671tUB88CTY7l1NBZRUM6kLOOEaNQJV9qesJw3/FXcwopND39B8AjX3YXEiQSzHTZa2P4ek8rClKw0E9wPsmHnB8UnSpo44kkUfRIs4tqQQKBgQC9Jr3/fMNTB7E5EptxIZV2Cbybhyfbm2kfawLpTMS0FvGl7OGZXISTt5gC3/EAvVyDS54/Zedk//ib/GsG6UzWbAsKqKspmGLTqjjfpRrEVp1Y7omgxE+1nq8WhfDbQzyqLziO1zGrjVd9i0I5XEOALAOWKbgvMSpO0VwfFcojgQKBgBXiUun7TpUcAudrPsvhuy819dCL1Xv/deaaf/O31AY6/xJzWd4mZCCUqb6/SVBqKuglHNHzOyYPE5lTkE5Z3NDIWYbEUlUvGYus4XpyCGA1vigxnckXFqt/VUiCDTDmQemPAe1+KeQfMMrCCgxQV+6GcoYUWy/LD7XkSB02qfvi
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnIRwzhtBz9qBOp3iANEOGNAQ3W8zQgyXXwpPhsSgP5mtsRMmuIbriEPcSoztHtBNwqiqwna3OZjman4yNr4NC4g8x5hn0RtyZphxl6HDSZRvxKEHq1kKkgDdxrHx58Vohmph0i26tvmHAax8Uvd8/JzqgBBtLuiB6KIjT3VZimrDMzyK+IVOwXGCr2fPOPOakARuckruMYIINoelicu5aYRI0TvKqWZVKrzHJ6bvqsxC3GldbxHAj1ITwc1GwmzrqXc2wbw/3m83Z4176F+Da7Qur5kQ/sQkqTS8Zz9DjsvE+3q7+lu1n13Afab7pEUgWstszVgyggz1EGtP2mUx1wIDAQAB
