#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

# DUBBO 配置
dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://172.31.3.48:2181?backup=172.31.3.48:2182,172.31.3.48:2183

jasypt:
  encryptor:
    property:
      prefix: RedE(   # 加密前缀
      suffix: )            # 加密后缀
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

spring:
  #数据库连接
  datasource:                                                                                                           #数据库连接
    url: RedE(PX4WS2d9HFU0k12T2JuznWwN5UgqdGfFxdScz69Li+XFFlMq62EnhWQ66d3e5i4c4ukEgnPwg8YFd1QvzjPdoKlIugvyY926FVTfFONcdk4kzP/xUnqZcbkNxbVhvGEE74XbKzp+aky+UWWjSY8wBi2bAGuhXEPwVrd3vIlV/iV1ThHei7v3F9b0vN6YA45N7Tz40sja0rX8L0MieGm0HLbVR13u/MzMmKAwMkXdL7UUlq2xUw6ZBCR0tDp0kVV15pFyAXG+fP8+OYiav06KQuG+kb0zGxPTi0Z0CSj90Zm0YPg8Cb46cvuW5MOB84GTRgh5rsiu/ir3USdT6MBWHRHecs7yJ2XxMvf32JUVMA0=)
    username: RedE(MQksLacGhzJsE+d+kFyr2A==)
    password: RedE(KsbR76xwwl4wdKPPkuPrB8pvdNRDNfD8FbLdrYfnPLqHzp7HfaaPRsrhhOdK1NSX)
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.3.48:7000
        - 172.31.3.48:7001
        - 172.31.3.48:7002
        - 172.31.3.48:7003
        - 172.31.3.48:7004
        - 172.31.3.48:7005
  # 邮件配置
  mail:
    from: support@redelectric.fr
    username: support@redelectric.fr
    host: smtp.ionos.fr
    password: RedE@Scooter54
    port: 465







# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys

