log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
dubbo:
  registry:
    address: zookeeper://10.1.1.142:2181?backup=10.1.1.142:2182,10.1.1.142:2183
  metadata-report:
    address: zookeeper://10.1.1.142:2181?backup=10.1.1.142:2182,10.1.1.142:2183
jasypt:
  encryptor:
    property:
      prefix: RedE(
      suffix: )
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

spring:
  datasource:                                                                                                           #数据库连接
    url: jdbc:mysql://10.1.2.238:2021/platform_prod?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: rede
    password: rede1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  redis:
    cluster:
      nodes:
        - 10.1.2.238:7000
        - 10.1.2.238:7001
        - 10.1.2.238:7002
        - 10.1.2.238:7003
        - 10.1.2.238:7004
        - 10.1.2.238:7005
  mail:
    host: smtp.gmail.com
    port: 465
    from: support@redelectric.fr
    username: support@redelectric.fr
    # 谷歌应用专属密码
    password: wxiqpwbypnthkrru
    properties:
      from: support@redelectric.fr
seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: ses-service-proxy-group
  registry:
    type: zk
    zk:
      server-addr: 10.1.1.142:2181
      cluster: default
      connect-timeout: 2000000
  config:
    type: zk
    zk:
      server-addr: 10.1.1.142:2181
      connect-timeout: 2000000
  service:
    disable-global-transaction: false
    vgroup-mapping:
      ses-admin-dev-group: default
  client:
    rm:
      report-success-enable: false