#日志路径
log:
  file:
    path: /data/java_service/logs3/@profile-active@
    max-size: 128MB
    max-history: 180

# DUBBO 配置
dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://192.168.2.200:2181

spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://192.168.2.200:3306/platform?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 192.168.2.200:7000
        - 192.168.2.200:7001
        - 192.168.2.200:7002
        - 192.168.2.200:7003
        - 192.168.2.200:7004
        - 192.168.2.200:7005
  # 邮件配置
  mail:
    from: 761291381@qq.com
    username: 761291381@qq.com
    host: smtp.qq.com
    password: qdiuwjkubkfsbfhh
    port: 587
