#日志路径
log:
  file:
    path: /data/java_service/logs/@profile-active@
    max-size: 128MB
    max-history: 180

# DUBBO 配置
dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://172.16.0.205:12181?backup=172.16.0.205:32181,172.16.0.205:32181

spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://172.16.0.205:3306/platform?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.16.0.205:7000
        - 172.16.0.205:7001
        - 172.16.0.205:7002
        - 172.16.0.205:7003
        - 172.16.0.205:7004
        - 172.16.0.205:7005

  # 邮件配置
  mail:
    from: support@redescooter.com
    username: support@redescooter.com
    host: smtp.exmail.qq.com
    password: RedE2019.scooter
    port: 465

# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys

