#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

# DUBBO 配置
dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://172.31.3.48:2181

spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://172.31.3.48:3306/platform_prod?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
    username: rede
    password: RedE2019!!
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.3.48:7000
        - 172.31.3.48:7001
        - 172.31.3.48:7002
        - 172.31.3.48:7003
        - 172.31.3.48:7004
        - 172.31.3.48:7005
  # 邮件配置
  mail:
    from: support@redescooter.com
    username: support@redescooter.com
    host: smtp.exmail.qq.com
    password: RedE2019.scooter
    port: 465

      
      
      
      
      
      
# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys

