#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

# DUBBO 配置
dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://172.31.5.73:2181?backup=172.31.5.73:2182,172.31.5.73:2183

jasypt:
  encryptor:
    property:
      prefix: RedE(   # 加密前缀
      suffix: )            # 加密后缀
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

spring:
  #数据库连接
  datasource:                                                                                                           #数据库连接
    url: RedE(RrOzdIhHs5/28riJycKnSlJP0O0/Uuv/NBz3A/QjfRvwIrvFHhP4yyD+qfsaLOLCnVBAGzwjL90RXoIImiVNuvYrS7/wNKp/ql6yQT2VaBoWvwK1C8v1IBfPxePpiCBWhyJzXqO8z7p8gK2Fz/mNh1T5GZtId6I620S4j/uZSY0pB5sSX68/p4Yu2663XCOEhwSNqM26E75yRvXZFU7nvFJYc8+b/IgpFGIc/LG/bvpiKAVAc/1taq4Jix6Z4C2GuLHWiHD7EkahgLkPmejWsLim17IL9vsQMNkBT7hi6byEueP3SpSHk1/3dJQwm7ES)
    username: RedE(MQksLacGhzJsE+d+kFyr2A==)
    password: RedE(KsbR76xwwl4wdKPPkuPrB8pvdNRDNfD8FbLdrYfnPLqHzp7HfaaPRsrhhOdK1NSX)
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.5.73:7000
        - 172.31.5.73:7001
        - 172.31.5.73:7002
        - 172.31.5.73:7003
        - 172.31.5.73:7004
        - 172.31.5.73:7005
  # 邮件配置
  mail:
    from: support@redelectric.fr
    username: support@redelectric.fr
    host: smtp.ionos.fr
    password: RedE@Scooter54
    port: 465







# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys

