#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://172.31.5.73:2181?backup=172.31.5.73:2182,172.31.5.73:2183

jasypt:
  encryptor:
    property:
      prefix: RedE(   # 加密前缀
      suffix: )            # 加密后缀
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

spring:
  #数据库连接
  datasource:                                                                                                           #数据库连接
    url: RedE(UDZYEghnNUjE0bmRmhjFyNyLVo6NeoaHqeW7IodzVfALduJNDFKpwT8HuCBgkXIwiZLYXOfxro2FmbYaFNHMmwghzp/cfVFFH01Xgnrn66fkk7ZXM/9qjsaOggNQQpTR567gS0RHdv5ZZAc+vHcikKmT64aGis9uMz+eMVAOZgvam1PAOWflBQiv6tnWHuvyPywffsjcpJKs6XhzRFG99Jy8hk3TPOAD/PAfuy9S61WGgtSfcdFcvnYMs5PdMuvAphSoM+DJWlAph8ltqddrW/ssmFYOjoMnYcACD0KP7K//7OabllUBQnDKc0javFXu)
    username: RedE(Iwkdtl5vHRu4yp//nI36SA==)
    password: RedE(y0jh9YjayhLACExUtMkmgqbPFubjOpMXpAyX5wlDtqAiJ8MGvouJt/L8SasnIHRH)
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.5.73:7000
        - 172.31.5.73:7001
        - 172.31.5.73:7002
        - 172.31.5.73:7003
        - 172.31.5.73:7004
        - 172.31.5.73:7005


# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys
