#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://39.108.92.232:3306/consumer?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
    #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 39.108.92.232:7000
        - 39.108.92.232:7001
        - 39.108.92.232:7002
        - 39.108.92.232:7003
        - 39.108.92.232:7004
        - 39.108.92.232:7005

## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://39.108.92.232:22181