#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://172.31.3.48:2181?backup=172.31.3.48:2182,172.31.3.48:2183

jasypt:
  encryptor:
    property:
      prefix: RedE(   # 加密前缀
      suffix: )            # 加密后缀
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

spring:
  #数据库连接
  datasource:                                                                                                           #数据库连接
    url: RedE(JXU/gps3UE5uRwZ1OCZJDiPi5Chr/d6ytrtHEdo/N6qjR48Pn9b4GtnpA/dp6tgIjXoFZlMWer6u+15aNGWTZRR+14ngiplTm17Gf3Wl2jFWX9Fltfafq14dABLOmAFTTsfbk/pz4CbX568uc33NIIUobDujTGG3lGWGqgMzG7us0xD0xqD3rRyUPTn0Uv0SYSMkc8slDjTDrukcLS1uwFLy5A7zXzoDuYErMyViZjPl0IoYdlge2AbDVWGe+ZQ6y4KYBkHIBxb4es+HMMwc63KWqpIep6tgm+pZMwtsQwCNsqVTvAqfi/2SkmTxWB2a)
    username: RedE(Iwkdtl5vHRu4yp//nI36SA==)
    password: RedE(y0jh9YjayhLACExUtMkmgqbPFubjOpMXpAyX5wlDtqAiJ8MGvouJt/L8SasnIHRH)
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.3.48:7000
        - 172.31.3.48:7001
        - 172.31.3.48:7002
        - 172.31.3.48:7003
        - 172.31.3.48:7004
        - 172.31.3.48:7005


# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys
