#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://192.168.2.211:2181
  metadata-report:
    address: zookeeper://192.168.2.211:2181
spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://192.168.2.211:3306/consumer?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: dev
    password: 1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 192.168.2.211:7000
        - 192.168.2.211:7001
        - 192.168.2.211:7002
        - 192.168.2.211:7003
        - 192.168.2.211:7004
        - 192.168.2.211:7005


seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: ses-service-mobile-c-group
  registry:
    type: zk
    zk:
      server-addr: 192.168.2.211:2181
      cluster: default
      connect-timeout: 2000000
  config:
    type: zk
    zk:
      server-addr: 192.168.2.211:2181
      connect-timeout: 2000000
  service:
    disable-global-transaction: false
    vgroup-mapping:
      ses-service-mobile-c-group: default
  client:
    rm:
      report-success-enable: false