log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
dubbo:
  registry:
    address: zookeeper://172.31.6.101:2181
  metadata-report:
    address: zookeeper://172.31.6.101:2181
spring:
  datasource:
    url: jdbc:mysql://172.31.6.136:2116/consumer_pre?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
    username: redpre
    password: pre.1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.6.136:7000
        - 172.31.6.136:7001
        - 172.31.6.136:7002
        - 172.31.6.136:7003
        - 172.31.6.136:7004
        - 172.31.6.136:7005




# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181

# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys
