#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://172.31.8.126:2181

spring:                                                                                                                 #spring config
  http:                                                                                                                 #上传配置
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 20MB
      enabled: true
  datasource:                                                                                                           #数据库连接
    url: jdbc:mysql://172.31.8.126:3306/operation?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
    username: root
    password: rede,1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      stat-view-servlet:                                                                                                #监控页面的用户名和密码 以及页面地址
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.8.126:7000
        - 172.31.8.126:7001
        - 172.31.8.126:7002
        - 172.31.8.126:7003
        - 172.31.8.126:7004
        - 172.31.8.126:7005

  swagger:                                                                                                              #swagger在线文档配置
    enabled: true                                                                                                       #是否启用swagger
    group:
      Sign-api:                                                                                                          #用户组api，可以配置多个组
        group-name: 1.Sign-API                                                                                          #api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: ROS Sign接口                                                                                              #api组的标题，会在swagger-ui的标题处显示
        description: 用户登录注销创建操作                                                                                  #api组的描述，会在swagger-ui的描述中显示
        base-package: com.redescooter.ses
        path-regex: /sign/token/.*                                                                                                 #匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                                                                                                 #匹配到的url在swagger中测试请求时加的url前缀
        version: v1.2.0                                                                                                 #Api版本
        license: RedE 公司内部传阅                                                                                        #授权协议
        license-url: '#'                                                                                                #授权协议地址
        terms-of-service-url:                                                                                           #服务条款地址
        contact:                                                                                                        #文档联系人
          name: 李加廷                                                                                                   #联系人名字
          email: jerry@redescooter.com                                                                                  #联系人邮箱
          url: https://github.com/mrjerryli                                                                             #联系地址

      customer-api:
        group-name: 2.Customer-API
        title: 客户相关的操作
        description: 客户相关的操作
        base-package: com.redescooter.ses
        path-regex: /consumer/.*
        path-mapping: /
        version: 1.2.0
        license: RedE 公司内部传阅
        license-url: '#'
        contact:
          name: Jerry
          email: Jerry@redescooter.com
          url: https://github.com/mrjerryli

      account-api:
        group-name: 3.Account-API
        title: 客户账户管理
        description: 客户账号相关操作
        base-package: com.redescooter.ses
        path-regex: /account/consumer/.*
        path-mapping: /
        version: 1.2.0
        license: RedE 公司内部传阅
        license-url: '#'
        contact:
          name: Jerry
          email: Jerry@redescooter.com
          url: https://github.com/mrjerryli                                                                      #联系地址

      factory-api:
        group-name: 4.factory-API
        title: 代工厂操作
        description: 代工厂操作
        base-package: com.redescooter.ses.web.ros
        path-regex: /factory/.*
        path-mapping: /
        version: 1.2.0
        license: RedE 公司内部传阅
        license-url: '#'
        contact:
          name: Jerry
          email: Jerry@redescooter.com
          url: https://github.com/mrjerryli

      supplier-api:
        group-name: 5.supplier-API
        title: 供应商操作
        description: 供应商操作
        base-package: com.redescooter.ses.web.ros
        path-regex: /supplier/.*
        path-mapping: /
        version: 1.2.0
        license: RedE 公司内部传阅
        license-url: '#'
        contact:
          name: Jerry
          email: Jerry@redescooter.com
          url: https://github.com/mrjerryli