#日志路径
log:
  file:
    path: logs/jerry
    max-size: 128MB
    max-history: 180

### xxl-job, datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xxl_job?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

xxl:
  job:
    accessToken: gfdsgfdssgsdfdfsdfsd
    i18n:
