#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

spring:
  datasource:
    url: jdbc:mysql://192.168.2.200:3306/tx-manager?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1qaz2wsx
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 192.168.2.200:7001
        - 192.168.2.200:7002
        - 192.168.2.200:7003
        - 192.168.2.200:7004
        - 192.168.2.200:7005
#lcn配置
lcn配置tx-lcn:
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    password: ${spring.datasource.username}
    username: ${spring.datasource.password}
  manager:
    admin-key: 123456
    concurrent-level: 160
    dtx-lock-time: ${tx-lcn.manager.dtx-time}
    dtx-time: 8000
    ex-url: /provider/email-to/653942945@qq.com
    ex-url-enabled: false
    heart-time: 300000
    host: 127.0.0.1
    port: 8070
    seq-len: 12
  message:
    netty:
      attr-delay-time: ${tx-lcn.manager.dtx-time}

dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://192.168.2.200:32181
