package com.redescooter.ses.mobile.rps.constant;

/**
 * @description: SequenceName
 * @author: Alex
 * @create: 2019/02/22 15:51
 */
public interface SequenceName {

    String OPE_ASSEMBLY_LOT_TRACE = "OPE_ASSEMBLY_LOT_TRACE";

    String OPE_STOCK_PROD_PRODUCT = "OPE_STOCK_PROD_PRODUCT";

    String OPE_STOCK_PROD_PART = "OPE_STOCK_PROD_PART";

    String OPE_ASSEMBLY_B_QC = "OPE_ASSEMBLY_B_QC";

    String OPE_ASSEMBLY_QC_TRACE = "OPE_ASSEMBLY_QC_TRACE";

    String OPE_ASSEMBLY_QC_ITEM = "OPE_ASSEMBLY_QC_ITEM";

    String OPE_PURCHAS_B_QC_ITEM = "OPE_PURCHAS_B_QC_ITEM";

    String OPE_PURCHAS_QC_TRACE = "OPE_PURCHAS_QC_TRACE";

    String OPE_PURCHAS_B_QC = "OPE_PURCHAS_B_QC";

    String OPE_ALLOCATE_B_TRACE = "OPE_ALLOCATE_B_TRACE";

    String OPE_PURCHAS_TRACE = "OPE_PURCHAS_TRACE";

    String OPE_STOCK = "OPE_STOCK";

    String OPE_STOCK_PURCHAS = "OPE_STOCK_PURCHAS";

    String OPE_STOCK_BILL = "OPE_STOCK_BILL";

    String OPE_PRODUCT_ASSEMBLY = "OPE_PRODUCT_ASSEMBLY";

    String OPE_PRODUCT_ASSEMBLY_B = "OPE_PRODUCT_ASSEMBLY_B";

    String OPE_ASSEMBIY_ORDER_TRACE = "OPE_ASSEMBIY_ORDER_TRACE";

    String OPE_ASSEMBLY_PREPARATION = "OPE_ASSEMBLY_PREPARATION";

    String OPE_ALLOCATE_TRACE = "OPE_ALLOCATE_TRACE";

    String OPE_PURCHAS_LOT_TRACE="OPE_PURCHAS_LOT_TRACE";

    String OPE_ALLOCATE_ORDER = "OPE_ALLOCATE_ORDER";

    String OPE_ALLOCATE_SCOOTER_B = "OPE_ALLOCATE_SCOOTER_B";

    String OPE_ALLOCATE_COMBIN_B = "OPE_ALLOCATE_COMBIN_B";

    String OPE_ALLOCATE_PARTS_B = "OPE_ALLOCATE_PARTS_B";

    String OPE_ENTRUST_ORDER = "OPE_ENTRUST_ORDER";

    String OPE_INVOICE_COMBIN_B = "OPE_INVOICE_COMBIN_B";

    String OPE_INVOICE_COMBIN_DETAIL_B = "OPE_INVOICE_COMBIN_DETAIL_B";

    String OPE_INVOICE_ORDER = "OPE_INVOICE_ORDER";

    String OPE_INVOICE_PARTS_B = "OPE_INVOICE_PARTS_B";

    String OPE_INVOICE_PARTS_DETAIL_B = "OPE_INVOICE_PARTS_DETAIL_B";

    String OPE_INVOICE_SCOOTER_B = "OPE_INVOICE_SCOOTER_B";

    String OPE_INVOICE_SCOOTER_DETAIL_B = "OPE_INVOICE_SCOOTER_DETAIL_B";

    String OPE_OP_TRACE = "OPE_OP_TRACE";

    String OPE_ORDER_STATUS_FLOW = "OPE_ORDER_STATUS_FLOW";

    String OPE_OUT_WH_COMBIN_B = "OPE_OUT_WH_COMBIN_B";

    String OPE_OUT_WH_PARTS_B = "OPE_OUT_WH_PARTS_B";

    String OPE_OUT_WH_SCOOTER_B = "OPE_OUT_WH_SCOOTER_B";

    String OPE_OUT_WHOUSE_ORDER = "OPE_OUT_WHOUSE_ORDER";

    String OPE_PURCHASE_COMBIN_B = "OPE_PURCHASE_COMBIN_B";

    String OPE_PURCHASE_ORDER = "OPE_PURCHASE_ORDER";

    String OPE_PURCHASE_PARTS_B = "OPE_PURCHASE_PARTS_B";

    String OPE_PURCHASE_SCOOTER_B = "OPE_PURCHASE_SCOOTER_B";

    String OPE_ORDER_QC_ITEM="OPE_ORDER_QC_ITEM";

    String OPE_ORDER_QC_TRACE="OPE_ORDER_QC_TRACE";

    String OPE_ORDER_SERIAL_BIND="OPE_ORDER_SERIAL_BIND";

    String OPE_ENTRUST_PRODUCT_SERIAL_NUM="OPE_ENTRUST_PRODUCT_SERIAL_NUM";

    String OPE_LOGISTICS_ORDER="OPE_LOGISTICS_ORDER";
}
