#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
# DUBBO 配置
dubbo: ##DUBBO配置
  registry: #注册中心
    address: zookeeper://172.31.6.101:2181
spring: #spring config
  http:                                                                                                                 #上传配置
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 20MB
      enabled: true
  datasource: #数据库连接
    url: jdbc:mysql://172.31.6.136:2116/website?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: rede
    password: 1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      stat-view-servlet: #监控页面的用户名和密码 以及页面地址
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.6.136:7000
        - 172.31.6.136:7001
        - 172.31.6.136:7002
        - 172.31.6.136:7003
        - 172.31.6.136:7004
        - 172.31.6.136:7005
  swagger:
    enabled: true
    group:
      auth-API:
        group-name: Auth API
        title: LogIn/LogOut
        description: LogIn/LogOut Service
        base-package: com.redescooter.ses.web.website.controller.LoginController
        path-regex: /auth/.*
        path-mapping: /
        version: v1.2.1
        license: RedE Circulation within the company
        license-url: '#'
        terms-of-service-url: https://api.redelectric.fr/
        contact:
          name: Jerry
          email: jerry@redescooter.com
          url: https://github.com/mrjerryli
      Website-API:
        group-name: Website API
        title: Website
        description: Website Service
        base-package: com.redescooter.ses.web.website.controller.business
        path-regex: /.*
        path-mapping: /
        version: v1.2.1
        license: RedE Circulation within the company
        license-url: '#'
        terms-of-service-url: https://api.redelectric.fr/
        contact:
          name: Jerry
          email: jerry@redescooter.com
          url: https://github.com/mrjerryli
      Config-API:
        group-name: Config API
        title: Config
        description: Config Service
        base-package: com.redescooter.ses.web.website.controller.config
        path-regex: /.*
        path-mapping: /
        version: v1.2.1
        license: RedE Circulation within the company
        license-url: '#'
        terms-of-service-url: https://api.redelectric.fr/
        contact:
          name: Jerry
          email: jerry@redescooter.com
          url: https://github.com/mrjerryli
## stripe pay
stripe:
  currency: eur
  payment_method_types: card
  payment_event: accept_a_payment
  publishable_key: pk_test_IsulbIcuGZ9e0z7K0EDECS5D00niQEDqL6
  secret_key: sk_test_8BOq2D5p1eS4pKyBbdjoWwgS00plcIG6cI
  receipt_email: etienne@redescooter.fr

oss: #阿里oss上传
  #调整最大文件大小为10M 默认单位为字节
  #oss 使用HTTPS、HTTP请求方式
  protocol: HTTPS

excel:
  folder: ${log.path}@profile-active@/projectExcel
sendinblue:
  listIds: 119

monday:
  url: https://api.monday.com/v2
  authorization: eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjI5MjE5MzMxLCJ1aWQiOjUwODM2NTksImlhZCI6IjIwMTktMTItMzBUMTA6NTU6MTEuMDAwWiIsInBlciI6Im1lOndyaXRlIn0.Z_dXLUCgiEUoHQXzeFlOqeG2jfSeiyKIdBNdwaAOKrA
  paramQuery: query
  paramVariables: variables
  httpMethod: POST
  MediaType: application/x-www-form-urlencoded
  #预订单业务
  orderFormBoardName: Pre Website Order
  orderFormBoardBackName: Pré-vente
  orderFormGroupName: Backlog
  #联系我们
  contactUsBoardName: Pre Website AboutUs
  contactUsBoardBackName: laisser un message
  contactUsGroupName: Backlog
  #订阅邮件
  subEmailBoardName: Pre Website Email
  subEmailBoardBackName: abonnement
  subEmailGroupName: Backlog
  # 工作空间 alex:132750
  workspaceId: 21182
  #模板Id
  templeteId: 581923336
  load-template: false

constant-us-email:
  sale-principal:
    - etienne@redescooter.fr
    - jerry@redescooter.com
