package com.redescooter.ses.web.ros.constant;

/**
 * @description: SequenceName
 * @author: Alex
 * @create: 2019/02/22 15:51
 */
public interface SequenceName {

    String OPE_SYS_USER = "OPE_SYS_USER";

    String OPE_SYS_USER_PROFILE = "OPE_SYS_USER_PROFILE";

    String OPE_CUSTOMER = "OPE_CUSTOMER";

    String CUSTOMERINQUIRY = "CUSTOMER_INQUIRY";

    String ORG_STAFF_POSITION = "ORG_STAFF_POSITION";

    String ORGSTAFF = "ORG_STAFF";

    String SALESAREA = "SALES_AREA";

    String ORG_POSITION_PERMISSION = "ORG_POSITION_PERMISSION";

    String ORG_POSITION = "ORG_POSITION";

    String ORG_DEPARTMENT = "ORG_DEPARTMENT";

    String PRODUCTION_PRODUCT = "PRODUCTION_PRODUCT";

    String PRODUCTION_IMPORT = "PRODUCTION_IMPORT";

    String PRODUCTION_DELIVERY_DETAIL = "PRODUCTION_DELIVERY_DETAIL";

    String PRODUCTION_DELIVERY = "PRODUCTION_DELIVERY";

    String PRODUCTION_DELIVERY_TRACE="PRODUCTION_DELIVERY_TRACE";

    String SALES_ORDER = "SALES_ORDER";

    String SALES_ORDER_PAYMENT = "SALES_ORDER_PAYMENT";

    String SALES_ORDER_DETAIL = "SALES_ORDER_DETAIL";

    String SALES_DELIVERY_ORDER = "SALES_DELIVERY_ORDER";

    String WAREHOUSE = "WAREHOUSE";

    String SALES_ORDER_TRACE = "SALES_ORDER_TRACE";

    String PRODUCT_ITEM = "PRODUCT_ITEM";

    String STOCK_BILLS = "STOCK_BILLS";

    String STOCK = "STOCK";

    String PRODUCT_PRICE = "PRODUCT_PRICE";

    String PRODUCT = "PRODUCT";

    String PRODUCT_PICTURE = "PRODUCT_PICTURE";

    String SALES_DELIVERY_ORDER_DETAIL = "SALES_DELIVERY_ORDER_DETAIL";

    String OPE_FACTORY="OPE_FACTORY";

    String OPE_FACTORY_TRACE="OPE_FACTORY_TRACE";

    String OPE_SUPPLIER="OPE_SUPPLIER";

    String OPE_SUPPLIER_TRACE="OPE_SUPPLIER_TRACE";

    String OPE_PARTS="OPE_PARTS";

    String OPE_PARTS_HISTORY_RECORD="OPE_PARTS_HISTORY_RECORD";


}
