package com.redescooter.ses.web.ros.constant;

/**
 * @description: SequenceName
 * @author: Alex
 * @create: 2019/02/22 15:51
 */
public interface SequenceName {

    String OPE_SYS_USER = "OPE_SYS_USER";

    String OPE_SYS_USER_PROFILE = "OPE_SYS_USER_PROFILE";

    String OPE_CUSTOMER = "OPE_CUSTOMER";

    String OPE_FACTORY = "OPE_FACTORY";

    String OPE_FACTORY_TRACE = "OPE_FACTORY_TRACE";

    String OPE_SUPPLIER = "OPE_SUPPLIER";

    String OPE_SUPPLIER_TRACE = "OPE_SUPPLIER_TRACE";

    String OPE_PARTS_PRODUCT = "OPE_PARTS_PRODUCT";

    String OPE_PARTS_PRODUCT_B = "OPE_PARTS_PRODUCT_B";

    String OPE_PARTS = "OPE_PARTS";

    String OPE_PARTS_TYPE = "OPE_PARTS_TYPE";

    String OPE_PARTS_DRAFT_HISTORY_RECORD = "OPE_PARTS_DRAFT_HISTORY_RECORD";

    String OPE_PRICE_SHEET = "OPE_PRICE_SHEET";

    String OPE_PRICE_SHEET_HISTORY = "OPE_PRICE_SHEET_HISTORY";

    String OPE_REGIONAL_PRICE_SHEET = "OPE_REGIONAL_PRICE_SHEET";

    String OPE_REGIONAL_PRICE_SHEET_HISTORY = "OPE_REGIONAL_PRICE_SHEET_HISTORY";

    String OPE_EXCLE_IMPORT = "OPE_EXCLE_IMPORT";

    String OPE_CUSTOMER_INQUIRY = "OPE_CUSTOMER_INQUIRY";

    String OPE_SYS_MENU = "OPE_SYS_MENU";

    String OPE_SYS_STAFF = "OPE_SYS_STAFF";

    String OPE_SYS_DEPT = "OPE_SYS_DEPT";

    String OPE_SYS_ROLE = "OPE_SYS_ROLE";

    String OPE_PURCHAS_B = "OPE_PURCHAS_B";

    String OPE_PURCHAS = "OPE_PURCHAS";

    String OPE_PARTS_DRAFT = "OPE_PARTS_DRAFT";

    String OPE_PURCHAS_PRODUCT = "OPE_PURCHAS_PRODUCT";

    String OPE_PURCHAS_TRACE = "OPE_PURCHAS_TRACE";

    String OPE_PURCHAS_PAYMENT = "OPE_PURCHAS_PAYMENT";

    String OPE_PURCHAS_B_QC = "OPE_PURCHAS_B_QC";

    String OPE_PURCHAS_B_QC_TRACE = "OPE_PURCHAS_B_QC_TRACE";

    String OPE_STOCK_BILL = "OPE_STOCK_BILL";

    String OPE_STOCK = "OPE_STOCK";

    String OPE_ALLOCATE = "OPE_ALLOCATE";

    String OPE_ALLOCATE_TRACE = "OPE_ALLOCATE_TRACE";

    String OPE_ALLOCATE_B = "OPE_ALLOCATE_B";

    String OPE_ASSEMBLY_ORDER_PAYMENT = "OPE_ASSEMBLY_ORDER_PAYMENT";

    String OPE_ASSEMBLY_ORDER = "OPE_ASSEMBLY_ORDER";

    String OPE_ASSEMBLY_ORDER_PART = "OPE_ASSEMBLY_ORDER_PART";

    String OPE_ASSEMBLY_B_ORDER = "OPE_ASSEMBLY_B_ORDER";

    String OPE_ASSEMBIY_ORDER_TRACE = "OPE_ASSEMBIY_ORDER_TRACE";

    String OPE_PART_DRAFT_QC_TEMPLATE = "OPE_PART_DRAFT_QC_TEMPLATE";

    String OPE_PART_DRAFT_QC_TEMPLATE_B = "OPE_PART_DRAFT_QC_TEMPLATE_B";

    String OPE_PRODUCT_QC_TEMPLATE = "OPE_PRODUCT_QC_TEMPLATE";

    String OPE_PRODUCT_QC_TEMPLATE_B = "OPE_PRODUCT_QC_TEMPLATE_B";

    String OPE_PART_QC_TEMPLATE = "OPE_PART_QC_TEMPLATE";

    String OPE_PART_QC_TEMPLATE_B = "OPE_PART_QC_TEMPLATE_B";

    String OPE_STOCK_PROD_PRODUCT = "OPE_STOCK_PROD_PRODUCT";

    String OPE_CUSTOMER_INQUIRY_B = "OPE_CUSTOMER_INQUIRY_B";

    String OPE_PAY_ORDER = "OPE_PAY_ORDER";

    String OPE_OUTWH_TRACE = "OPE_OUTWH_TRACE";

    String OPE_OUTWH_ORDER = "OPE_OUTWH_ORDER";

    String OPE_OUTWH_ORDER_B = "OPE_OUTWH_ORDER_B";

    String OPE_FR_STOCK="OPE_FR_STOCK";

    String OPE_FR_STOCK_BILL="OPE_FR_STOCK_BILL";

    String OPE_FR_STOCK_PRODUCT="OPE_FR_STOCK_PRODUCT";

    String OPE_CONTACT_US = "OPE_CONTACT_US";

    String OPE_CONTACT_US_TRACE = "OPE_CONTACT_US_TRACE";
}
