#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://172.31.5.73:2181?backup=172.31.5.73:2182,172.31.5.73:2183

jasypt:
  encryptor:
    property:
      prefix: RedE(   # 加密前缀
      suffix: )            # 加密后缀
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

spring:
  #数据库连接
  datasource:                                                                                                           #数据库连接
    url: RedE(0Xz7ByNJonUWlBQew/CLzFYTX1UCXZsWfYv8CmZHgdTaAgYfuCRRnc/pzIlO5nvvaMnWp9w37zU3+eqYarR/5maW0n4Mf8bMcsCF5agLK8+9m7bTWTG401wkkCvE/Yjj2WNRokTEVttVYDxrt+UEkN9GP7VsBgNzl/s5oOgqUbQA8ih17JkCTSsvh6MfI/aKb7ApbNdBq61E+Axe2Ui4h2VcA8NE7GSmlohZ8BbqoQ8v9acA/NEZ7p5FYHvDPf2+Xyaf3kyD9VjINgI9c6VGWcu1HqFZ+Wm3hvxvQK0ZeSjx23UAgme2RjIQzfyEcx/U)
    username: RedE(0n5g6gKjHGV7owQCqpLVqQ==)
    password: RedE(Ks+s0aGo+bpmurenIIzzqHw0Yp70hLaYmyN+0kuEm96s8nbl28RfjY6/ocV+RjuI)
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.5.73:7000
        - 172.31.5.73:7001
        - 172.31.5.73:7002
        - 172.31.5.73:7003
        - 172.31.5.73:7004
        - 172.31.5.73:7005


# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys
