#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
dubbo:
  registry:
    address: zookeeper://10.0.1.19:2181
  metadata-report:
    address: zookeeper://10.0.1.19:2181
spring:
  datasource:
    url: jdbc:mysql://10.0.1.19:3306/corporate_pre?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: sespre
    password: sespre=[;.-pl,]
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  redis:
    cluster:
      nodes:
        - 10.0.1.19:7000
        - 10.0.1.19:7001
        - 10.0.1.19:7002
        - 10.0.1.19:7003
        - 10.0.1.19:7004
        - 10.0.1.19:7005

seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: ses-service-mobile-b-group
  registry:
    type: zk
    zk:
      server-addr: 10.0.1.19:2181
      cluster: default
      connect-timeout: 2000000
  config:
    type: zk
    zk:
      server-addr: 10.0.1.19:2181
      connect-timeout: 2000000
  service:
    disable-global-transaction: false
    vgroup-mapping:
      ses-service-mobile-b-group: default
  client:
    rm:
      report-success-enable: false