#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://172.31.3.48:2181?backup=172.31.3.48:2182,172.31.3.48:2183

jasypt:
  encryptor:
    property:
      prefix: RedE(   # 加密前缀
      suffix: )            # 加密后缀
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

spring:
  #数据库连接
  datasource:                                                                                                           #数据库连接
    url: RedE(4ELkr6ulwyn8FN0boYsJpemf//goDClfF6Y7Z1JOEYcL2T/QtHfN2Et2aILspoNVJ3AqM1AXdfsjzfXx8pYVGlXgchWh/tNeYVsezuy4ePoHQFESyi6Sxv83wiDPno2CN2EtQgzha6rzg31JE5iRMzAyOBMZ/6N4iYMY7S2xUNsNsvcMzdEBRHs3UKHzIRru91MV9Nl7kWwz0hBJO643blztA+prQTzZ2NoIh8QiQ+ITiBBqH5toWK02b+duprTIqKjmBuUe6MbMpIDB8BXm1wjcOueYzdb9OMNCf9qKbznKH7NwGKxdnUvA96teqsUg)
    username: RedE(0n5g6gKjHGV7owQCqpLVqQ==)
    password: RedE(Ks+s0aGo+bpmurenIIzzqHw0Yp70hLaYmyN+0kuEm96s8nbl28RfjY6/ocV+RjuI)
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.3.48:7000
        - 172.31.3.48:7001
        - 172.31.3.48:7002
        - 172.31.3.48:7003
        - 172.31.3.48:7004
        - 172.31.3.48:7005


# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys
