#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
# DUBBO 集群配置
#dubbo:                                                                                                                  ##DUBBO配置
#  registry:                                                                                                             #注册中心
#    address: zookeeper://172.31.8.126:2181?backup=172.31.8.126:2182,172.31.8.126:2183
## DUBBO 单节点配置
dubbo:
  registry: #注册中心
    address: zookeeper://172.31.8.126:2181
  metadata-report:
    address: zookeeper://172.31.8.126:2181
spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://172.31.8.126:3306/corporate?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rede,1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.8.126:7000
        - 172.31.8.126:7001
        - 172.31.8.126:7002
        - 172.31.8.126:7003
        - 172.31.8.126:7004
        - 172.31.8.126:7005

# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181

# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys


seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: ses-service-mobile-b-group
  registry:
    type: zk
    zk:
      server-addr: 172.31.8.126:2181
      cluster: default
      connect-timeout: 2000000
  config:
    type: zk
    zk:
      server-addr: 172.31.8.126:2181
      connect-timeout: 2000000
  service:
    disable-global-transaction: false
    vgroup-mapping:
      ses-service-mobile-b-group: default
  client:
    rm:
      report-success-enable: false
