#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://192.168.2.200:52181
  metadata-report:
    address: zookeeper://192.168.2.200:52181
spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://47.105.215.239:3306/corporate?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rede,1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 192.168.2.200:7000
        - 192.168.2.200:7001
        - 192.168.2.200:7002
        - 192.168.2.200:7003
        - 192.168.2.200:7004
        - 192.168.2.200:7005

