#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
dubbo:
  registry:
    address: zookeeper://172.28.193.226:2181
  metadata-report:
    address: zookeeper://172.28.193.226:2181
spring:                                                                                                                 #spring config
  http:                                                                                                                 #上传配置
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 20MB
      enabled: true
  datasource:                                                                                                           #数据库连接
    url: jdbc:mysql://172.28.193.226:3306/operation_test?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: rede
    password: test.1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      stat-view-servlet:                                                                                                #监控页面的用户名和密码 以及页面地址
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.28.193.226:7000
        - 172.28.193.226:7001
        - 172.28.193.226:7002
        - 172.28.193.226:7003
        - 172.28.193.226:7004
        - 172.28.193.226:7005

excel:
  folder: ${log.path}@profile-active@/projectExcel
sendinblue:
  listIds: 119

seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: ses-wh-fr-group
  registry:
    type: zk
    zk:
      server-addr: 172.28.193.226:2181
      cluster: default
      connect-timeout: 2000000
  config:
    type: zk
    zk:
      server-addr: 172.28.193.226:2181
      connect-timeout: 2000000
  service:
    disable-global-transaction: false
    vgroup-mapping:
      ses-wh-fr-group: default
  client:
    rm:
      report-success-enable: false
