#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://47.105.215.239:2181?backup=47.105.215.239:2182,47.105.215.239:2183

spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://172.31.8.126:3306/platform?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rede,1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.8.126:7000
        - 172.31.8.126:7001
        - 172.31.8.126:7002
        - 172.31.8.126:7003
        - 172.31.8.126:7004
        - 172.31.8.126:7005
