#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

dubbo:                                                                                                                  #DUBBO 配置
  registry:                                                                                                             #注册中心
    address: zookeeper://172.31.3.48:2181?backup=172.31.3.48:2182,172.31.3.48:2183

jasypt:
  encryptor:
    property:
      prefix: RedE(   # 加密前缀
      suffix: )            # 加密后缀
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

spring:
  #数据库连接
  datasource:                                                                                                           #数据库连接
    url: RedE(opJKCz5qCJq2uqYcLca43V0Iu0SdD6Ov4B/tVwYrE4dxhnK4pyfpBHqjLNV2RBuN9HwByqEQMO2sj/Dvyuh/vfhubqS5Oa9KGqNwn9enfjxM1NTdn8KMNOd8VJFyOfLL+fmu9Kh9PR2UckSk8xw/g6TWIUfR3tPNAmuSM3nVDcsMZUU7WVeh8Hl/zAeofqqQ36mneyicFoxpxZ3h/C9nmqgZK4coe2PSr+p9Y6X/v0FlWztAxMVVro1cXGIUUI73a+orrws49lpum37wk55Po6lmJ+N5C0kvSh2DCWCR0iEsflS1ycAFD39ZLMXa8s65wLbu6WGR9HzWm/6/SkOSQ45kKGcObZtwS4sSaqon3zk=)
    username: RedE(KZHmf/o1q2wBM1jYA/29Sw==)
    password: RedE(fHRxmETbcpUpah/tH49sOY+8Fl86wduHyV7en4kfiEsUeC/5OlB1ZwCTv6lPKVPS)
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.3.48:7000
        - 172.31.3.48:7001
        - 172.31.3.48:7002
        - 172.31.3.48:7003
        - 172.31.3.48:7004
        - 172.31.3.48:7005



# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys
