
log:                                                                                                                    #日志路径
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

# DUBBO 配置
dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://172.31.6.101:2181

spring:                                                                                                                 #spring config
  datasource:                                                                                                           #数据库连接
    url: jdbc:mysql://172.31.6.136:2116/platform?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: rede
    password: 1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.6.136:7000
        - 172.31.6.136:7001
        - 172.31.6.136:7002
        - 172.31.6.136:7003
        - 172.31.6.136:7004
        - 172.31.6.136:7005
saas-login-extreme-experience:
    web: true
    app-android: false
    app-ios: false
