#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
dubbo:
  registry:
    address: zookeeper://10.1.1.142:2181?backup=10.1.1.142:2182,10.1.1.142:2183
  metadata-report:
    address: zookeeper://10.1.1.142:2181?backup=10.1.1.142:2182,10.1.1.142:2183
spring:
  datasource:
    url: jdbc:mysql://10.1.2.53:2021/platform_prod?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: rede
    password: rede1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 10.1.2.53:7000
        - 10.1.2.53:7001
        - 10.1.2.53:7002
        - 10.1.2.53:7003
        - 10.1.2.53:7004
        - 10.1.2.53:7005

saas-login-extreme-experience:
    web: true
    app-android: false
    app-ios: false
