#日志路径
log:
  file:
    path: /data/java_service/logs/@profile-active@
#    path: logs/@profile-active@
    max-size: 128MB
    max-history: 180

## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://10.211.55.5:12181?backup=10.211.55.5:22181,10.211.55.5:32181
  metadata-report:
    address: zookeeper://10.211.55.5:12181?backup=10.211.55.5:22181,10.211.55.5:32181
  config-center:
    address: zookeeper://10.211.55.5:12181?backup=10.211.55.5:22181,10.211.55.5:32181

spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://10.211.55.5:3306/platform?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
    username: root
    password: 1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 10.211.55.5:7000
        - 10.211.55.5:7001
        - 10.211.55.5:7002
        - 10.211.55.5:7003
        - 10.211.55.5:7004
        - 10.211.55.5:7005


