
log:                                                                                                                    #日志路径
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

# DUBBO 集群配置
#dubbo:                                                                                                                  ##DUBBO配置
#  registry:                                                                                                             #注册中心
#    address: zookeeper://192.168.2.211:2181?backup=192.168.2.211:2182,192.168.2.211:2183
## DUBBO 单节点配置
dubbo:
  registry: #注册中心
    address: zookeeper://192.168.2.211:2181
  metadata-report:
    address: zookeeper://192.168.2.211:2181
spring:                                                                                                                 #spring config
  datasource:                                                                                                           #数据库连接
    url: jdbc:mysql://106.14.33.94:3306/platform_test?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: rede
    password: test.1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 192.168.2.211:7000
        - 192.168.2.211:7001
        - 192.168.2.211:7002
        - 192.168.2.211:7003
        - 192.168.2.211:7004
        - 192.168.2.211:7005
saas-login-extreme-experience:
    web: true
    app-android: false
    app-ios: false

seata:
  enabled: true
  enable-auto-data-source-proxy: true
  tx-service-group: ses-service-foundation-group
  registry:
    type: zk
    zk:
      server-addr: 192.168.2.211:2181
      cluster: default
      connect-timeout: 2000000
  config:
    type: zk
    zk:
      server-addr: 192.168.2.211:2181
      connect-timeout: 2000000
  service:
    disable-global-transaction: false
    vgroup-mapping:
      ses-service-foundation-group: default
  client:
    rm:
      report-success-enable: false
