#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180
spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/platform?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&rewriteBatchedStatements=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 192.168.0.111:7000
        - 192.168.0.111:7001
        - 192.168.0.111:7002
        - 192.168.0.111:7003
        - 192.168.0.111:7004
        - 192.168.0.111:7005
## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://192.168.0.111:2181
