#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

dubbo:                                                                                                                  #DUBBO 配置
  registry:                                                                                                             #注册中心
    address: zookeeper://172.31.5.73:2181?backup=172.31.5.73:2182,172.31.5.73:2183

jasypt:
  encryptor:
    property:
      prefix: RedE(   # 加密前缀
      suffix: )            # 加密后缀
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

spring:
  #数据库连接
  datasource:                                                                                                           #数据库连接
    url: RedE(w67gcY8zXtgJOayQO8BSE6SRYBVKRqEzB0JoX37pGcmutm+8Q1nO/vYitxVhbCOoC2txI3GrFV5dPEyvz0x/G0yKkICoZwRE6HrnFbmnBrg3bbqVqsn4BfdBChWxNJDEpaPHEXehsU6XCMJorHbuNltkBQxEzcqiiGGM9fScWLqp7pX7KFTUuRZ3QoScHIwFaLknxdPSusGJ6X3nhLF43ix9y3k9E6qg+TvQWGGjH2hjjOnPqllja/Cr59si0GsXoYAXp5UV+0W1V9zMeH+ojFPNIwZqpvlHRTKRU4jKJi2F/Hv4TbxzEFQ0am9XnYQd)
    username: RedE(KZHmf/o1q2wBM1jYA/29Sw==)
    password: RedE(fHRxmETbcpUpah/tH49sOY+8Fl86wduHyV7en4kfiEsUeC/5OlB1ZwCTv6lPKVPS)
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.5.73:7000
        - 172.31.5.73:7001
        - 172.31.5.73:7002
        - 172.31.5.73:7003
        - 172.31.5.73:7004
        - 172.31.5.73:7005



# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.t.xqcx.com:32181?backup=zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181


# sentinel 规则文件位置，以下依次是：流控规则，降级规则，系统规则文件位置
#sentinel:
#  zk-address: zk1.t.xqcx.com:32181,zk2.t.xqcx.com:32181,zk3.t.xqcx.com:32181
#  groupid: hdg_sentinel
#  flow-dataid: @project.artifactId@-flow
#  degra-dedataid: @project.artifactId@-degra
#  system-dataid: @project.artifactId@-sys
