#Springboot 基础配置
server:
  port: ${random.int[10000,19999]}
spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @profile-active@
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
    encoding: UTF-8
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  #数据库连接
  datasource:
    # 是否开启 SQL日志输出，生产环境建议关闭，有性能损耗
    p6spy: true
    druid:
      stat-view-servlet:
        loginUsername: admin
        loginPassword: admin@RedE2019
    dynamic:
      druid:
        initial-size: 3
        max-active: 8
        min-idle: 2
        max-wait: -1
        min-evictable-idle-time-millis: 30000
        max-evictable-idle-time-millis: 30000
        time-between-eviction-runs-millis: 0
        validation-query: select 1
        validation-query-timeout: -1
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        pool-prepared-statements: true
        max-open-prepared-statements: 100
        filters: stat,wall
        share-prepared-statements: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    open-in-view: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  # swagger配置
  swagger:
    enabled: false                                       # 是否启用swagger
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  #REDIS集群配置
  redis:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 200      # 连接池中的最大空闲连接
        min-idle: 50       # 连接池中的最小空闲连接

dubbo:                                                                                                                  #DUBBO 配置
  application:
    id: @project.artifactId@
    name: @project.artifactId@
    qos-enable: false                                                                                                   #是否启动QoS
    qos-accept-foreign-ip: false                                                                                        #是否允许远程访问
    logger: log4j
  registry:
    check: false                                                                                                        #注册中心不存在时，是否报错
    group: ses
  scan:
    base-packages: com.redescooter.ses                                                                                  #服务暴露与发现消费所在的package
  provider:                                                                                                             #服务提供者缺省值配置
    timeout: 30000
    threads: 300
  consumer:                                                                                                             #服务消费者缺省值配置
    check: false                                                                                                        #启动时检查提供者是否存在，true报错，false忽略
    timeout: 20000
    filter: dubboAccessLogFilter
  protocol:
    port: -1
    threads: 300
    name: dubbo

#REDIS配置
redis:
  max-total: 10000
  max-idle: 200
  min-Idle: 50
  timeout: 3000
  max-attempts: 5

#MYBATIS配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybaits-plus配置，此配置 不影响原始的mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  typeAliasesPackage: com.redescooter.ses.service.hub.source.consumer.dm,com.redescooter.ses.service.hub.source.corporate.dm,com.redescooter.ses.service.hub.source.operation.dm
  check-config-location: true
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #配置逻辑删除字段为1是删除
    logic-delete-value: 1
    #配置逻辑删除字段为0是未删除
    logic-not-delete-value: 0
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
  configuration:
    #是否开启自动驼峰命名规则（camel case）映射
    map-underscore-to-camel-case: true
    #全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存
    cache-enabled: false
    call-setters-on-nulls: true
    #配置JdbcTypeForNull, oracle数据库必须配置
    jdbc-type-for-null: 'null'
    #MyBatis 自动映射时未知列或未知属性处理策略 NONE：不做任何处理 (默认值), WARNING：以日志的形式打印相关警告信息, FAILING：当作映射失败处理，并抛出异常和详细信息
    auto-mapping-unknown-column-behavior: warning
