server:                                                                                                                 #Springboot 基础配置
  port: 28190
  servlet:
    context-path: /ses/t/ros/w/api
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @profile-active@
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
    encoding: UTF-8
  datasource:                                                                                                           #数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  #REDIS集群配置
  redis:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 200      # 连接池中的最大空闲连接
        min-idle: 50       # 连接池中的最小空闲连接

  http:                                                                                                                 #编码格式
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  freemarker:
    check-template-location: false
                                                                                                                        #Springboot-actuator 配置,后续添加prometheus采集指标数据,Grafana可视化监控数据
management:
  server:
    port: 28188
    servlet:
      context-path: "/management"
  endpoints:
    enabled-by-default: true
    web:
      base-path: "/monitor"
      exposure:                                                                                                         #设置暴露所有端点
        include: "*"
  endpoint:
    shutdown:                                                                                                           #设置单个端点（/shutdown）可用
      enabled: true

dubbo:                                                                                                                  #DUBBO 配置
  application:
    id: @project.artifactId@
    name: @project.artifactId@
    qos-enable: false                                                                                                   #是否启动QoS
    qos-accept-foreign-ip: false                                                                                        #是否允许远程访问
    logger: log4j
  registry:
    check: false                                                                                                        #注册中心不存在时，是否报错
    group: ses
  scan:
    base-packages: com.redescooter.ses                                                                                  #服务暴露与发现消费所在的package
  provider:                                                                                                             #服务提供者缺省值配置
    timeout: 30000
    threads: 300
  consumer:                                                                                                             #服务消费者缺省值配置
    check: false                                                                                                        #启动时检查提供者是否存在，true报错，false忽略
    timeout: 20000
    filter: dubboAccessLogFilter
  protocol:
    port: -1
    threads: 300
    name: dubbo

mybatis:                                                                                                                #MYBATIS配置
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl                                                               #打印sql

mybatis-plus:                                                                                                           #mybaits-plus配置，此配置 不影响原始的mybatis
  mapper-locations: classpath*:mapper/base/*Mapper.xml,classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.redescooter.ses.web.ros.vo,com.redescooter.ses.web.ros.dm
  global-config:                                                                                                        #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3                                                                                                          #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1                                                                                                   #驼峰下划线转换
    db-column-underline: true                                                                                           #配置逻辑删除字段为1是删除
    logic-delete-value: 1                                                                                               #配置逻辑删除字段为0是未删除
    logic-not-delete-value: 0                                                                                           #刷新mapper 调试神器
    refresh-mapper: true                                                                                                #数据库大写下划线转换
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

oss:                                                                                                                    #阿里oss上传
  internalEndpoint: oss-accelerate.aliyuncs.com
  accessKeyId: LTAIDUpZRjkFVCze
  secretAccesskey: lVM6XOqSdrdgJ3brHRcdSUOAVdxcS5
  defaultBucketName: rede
  publicEndpointDomain: oss-accelerate.aliyuncs.com
  maxFileSize: 10485760


#前端请求私钥
Request:
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC+7WGoCsjCnwMYFgHA+Y8ys463WIhvzJNV7y8VH6DCAcpnuuw8YoVi199tjn6EMo/cdOii4z934EWsYMy0+OyE1tlPhOLThor3otkGLqr9UaFHxyzITQyOsZbrYele0JFuVN66aroTwT4pWYk9jG7IaWX1it83eTaZY0RBU2+FsfAvDFxAWa5AcH/CcS+z9m8EVSmhpetZkLl3v9t0CH/eosLUAcVkhOizzZOlb3/ENgyIgGhEfy5/nKZtZom8BMjJLsTsiCKvCUfNNJlhEUadGg7JumRh+UOjjWqrxSyNe+YSsnfLQaYkxU3NZFrLyAWo7y+4olDdJZMNWeE8w7ZNAgMBAAECggEBALDzyYK5HABk57U3EEEOCs3u5OLAxxL3A8ate3GUcqXciv9AmxoMJZvKf2VGn7NeOT8Vi1cMTxKHZYux24gO/QbRKW8tthxdogaJg6LbNda6BURFMRgjcPP/W+SkRmp924vqVNNpfzQ38ajZNv04XqSYKss7/k2nphbbjbMN5Vp+SjQ8jHr4iN5z84NRLZbE8RRMn20s9rNorumdcJGFuWqUjryUMyFF/cwOtEwBIgLGmOiVsEqFOgIpWreUTibJqmN4M020B+fL+Cf9qGpxqWkdcPovMI8H889JN/8jMvDmGR1KDP2qceQE3HbsBot2KwnbWgzAVG8sWxzyeY86CoECgYEA4ndk2Ky7RYWAsmzUeZpzD1ftdWOIWDGWfZw8q+qcc/MaJQqaLKwv0yvjng9xDdNK9EQjz1FAAOSulirvdPpDPUHVt923QRIT3dl6nD/GgbdRUpMw01N8ci+2KCYRWEmE7tnEEUzfyeUZGjVei5ilPn5U17ULSdy1wBrRrq+i0ykCgYEA19OCn7/nBTejK7rHTz6kbzHz763R5X4g1J8oGwYqxiPzmKx6xCRXcsBJlKMAurh9VC+7hn0tuiRqaO7EAA7is4NKdN2xP12FDPFKjQCLK44908QqvdL1CvGrkKTpUC1EugLI1FiwQV+59MvCll7/0bybPNqp68blBC+wWCw+MoUCgYEApP0a6YiePv4OTu9etOFDJlCG3VkQQkCORSEISq94IDliOM5KmHUxuoVlJQhW8x2Wo/Loq+ej24K/dwP8xJp3Vi+ahoPvOGb1NlF1NFR6SJLHmoNFtRBDv+TmrsVdKZcWU/UvFPOOrsZLzX5ITSd+a9MZ+LUbbkpv128yiDPJSlECgYBl8AagQVlyQ2cUPnHo4eN0iZl3uReMV1hWVJ3ytaT6VPy3Pa/2eFu9XUjjpWGwz3aSjsD5sqIoaw6/ZRa6GE3HD9nY/OS80wUGqejWVE1nUxWssdimM799Xcv0049HSTpOyQXmFcWZ+wavspXDxDb77yM7SOQ88oI0yfl2i98MqQKBgA+uhYSVt4sBW1kiiJshXKlZTeoM8TKSJqkXxE1oAa1aBJI+jwDWe+JBOXs5ExeoMpzYDgTRZ5UwQM0HfwuWSgHF69asz3PAKST4eLUoHP9pvaqRxONHKO9fdRcLAH/0HVsTzk7tCOQa4/GB5T4SKXPDPn3M/JiCXZ00npMvmPeW
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvu1hqArIwp8DGBYBwPmPMrOOt1iIb8yTVe8vFR+gwgHKZ7rsPGKFYtffbY5+hDKP3HToouM/d+BFrGDMtPjshNbZT4Ti04aK96LZBi6q/VGhR8csyE0MjrGW62HpXtCRblTeumq6E8E+KVmJPYxuyGll9YrfN3k2mWNEQVNvhbHwLwxcQFmuQHB/wnEvs/ZvBFUpoaXrWZC5d7/bdAh/3qLC1AHFZITos82TpW9/xDYMiIBoRH8uf5ymbWaJvATIyS7E7IgirwlHzTSZYRFGnRoOybpkYflDo41qq8UsjXvmErJ3y0GmJMVNzWRay8gFqO8vuKJQ3SWTDVnhPMO2TQIDAQAB


