#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://192.168.2.200:52181

# xxl-job config
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://127.0.0.1:48099
    ### xxl-job executor address
    executor:
      ip:
      port: 9998
      appname: ses-local-executor
      address:
      ### xxl-job log path
      logpath: ${log.path}@profile-active@/@project.artifactId@
      ### xxl-job log retention days
      logretentiondays: 1
    ### xxl-job, access token
    accessToken:
