#日志路径
log:
  file:
    path: logs/@profile-active@
    max-size: 128MB
    max-history: 180

dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://192.168.2.200:22181

# xxl-job config
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://localhost:48091/rede/job/admin/
    ### xxl-job executor address
    executor:
      appname: ses-two
      ip:
      port: 9977
      ### xxl-job log path
      logpath: logs/@profile-active@
      ### xxl-job log retention days
      logretentiondays: 30
    ### xxl-job, access token
    accessToken: gfdsgfdssgsdfdfsdfsd
