#日志路径
log:
  file:
    path: /data/java_service/logs/@profile-active@
    max-size: 128MB
    max-history: 180
# DUBBO 配置
dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://127.0.0.1:2181

# xxl-job config
xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://127.0.0.1:48090/rede/job/admin
    ### xxl-job executor address
    executor:
      appname: ses-one
      ip:
      port: 48098
      ### xxl-job log path
      logpath: /data/java_service/logs/@profile-active@
      ### xxl-job log retention days
      logretentiondays: -1
    ### xxl-job, access token
    accessToken: a02d4b20ab655ec85277c86e