#Springboot 基础配置
server:
  port: ${random.int[10000,19999]}
spring:
  application:
    name: ses-service-foundation
  profiles:
    active: local
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
    encoding: UTF-8
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      # 监控页面的用户名和密码 以及页面地址
      stat-view-servlet:
        login-username: admin
        login-password: admin@RedE2019
        enabled: false
        url-pattern: /druid/*
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  # swagger配置
  swagger:
    enabled: false                                       # 是否启用swagger
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

# DUBBO 配置
dubbo:
  application:
    id: ses-service-foundation
    name: ses-service-foundation
    qos-enable: false # 是否启动QoS
    qos-accept-foreign-ip: false #是否允许远程访问
  registry:
    check: false # 注册中心不存在时，是否报错
  scan:
    base-packages: com.redescooter.ses #服务暴露与发现消费所在的package
  provider: #服务提供者缺省值配置
    timeout: 30000
    threads: 300
  consumer: #服务消费者缺省值配置
    check: false # 启动时检查提供者是否存在，true报错，false忽略
    timeout: 20000
    filter: dubboAccessLogFilter
  protocol:
    port: -1
    threads: 300

#REDIS配置
redis:
  max-total: 10000
  max-idle: 200
  min-Idle: 50
  timeout: 3000
  max-attempts: 5

#MYBATIS配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    #打印sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#mybaits-plus配置，此配置 不影响原始的mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/base/*Mapper.xml,classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.redescooter.ses.service.foundation.dm.base
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #配置逻辑删除字段为1是删除
    logic-delete-value: 1
    #配置逻辑删除字段为0是未删除
    logic-not-delete-value: 0
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
