#日志路径
log:
  file:
    path: logs/local
    max-size: 128MB
    max-history: 180

spring:
  #数据库连接
  datasource:
    url: jdbc:mysql://192.168.2.200:3306/platform_1213?useUnicode=true&amp;characterEncoding=UTF8&amp;allowMultiQueries=true&amp;rewriteBatchedStatements=true&amp;zeroDateTimeBehavior=convertToNull&serverTimezone=UTC&useLegacyDatetimeCode=false&useSSL=false
    username: root
    password: 1qaz2wsx
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000

#REDIS配置
redis:
  redis-address: 192.168.2.200:7000;192.168.2.200:7001;192.168.2.200:7002;192.168.2.200:7003;192.168.2.200:7004;192.168.2.200:7005

## DUBBO 配置
dubbo:
  registry: #注册中心
    address: zookeeper://192.168.2.200:32181
  metadata-report: #元数据中心
    address: zookeeper://192.168.2.200:32181
    timeout: 30000
  config-center: #配置中心
    address: zookeeper://192.168.2.200:32181
