#Springboot 基础配置
server:
  port: ${random.int[10000,19999]}
spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @profile-active@
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
    encoding: UTF-8
  #数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      # 监控页面的用户名和密码 以及页面地址
      stat-view-servlet:
        login-username: admin
        login-password: admin
        enabled: false
        url-pattern: /druid/*
  #REDIS集群配置
  redis:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
    timeout: 6000  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 200      # 连接池中的最大空闲连接
        min-idle: 50       # 连接池中的最小空闲连接

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
  # 邮件配置
  mail:
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          auth: true
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
            required: true

  # swagger配置
  swagger:
    enabled: false                                       # 是否启用swagger
#DUBBO 配置
dubbo:
  application:
    id: @project.artifactId@
    name: @project.artifactId@
    #是否启动QoS
    qos-enable: false
    #是否允许远程访问
    qos-accept-foreign-ip: false
    logger: log4j
  #服务消费者引用服务配置
  reference:
    check: false
  #注册中心配置
  registry:
    simplified: true
    #注册中心不存在时，是否报错
    check: false
    register: true
    subscribe: true
    group: ses
    protocol: zookeeper
  # Dubbo服务暴露与发现消费所在的package
  scan:
    base-packages: com.redescooter.ses
  provider: #服务提供者缺省值配置
    dynamic: true
    timeout: 30000
    threads: 300
  #服务消费者缺省值配置
  consumer:
    #启动时检查提供者是否存在，true报错，false忽略
    check: false
    timeout: 20000
    filter: dubboAccessLogFilter
  protocol:
    register: true
    port: -1
    threads: 300
    name: dubbo
#mybaits-plus配置，此配置 不影响原始的mybatis
mybatis-plus:
  mapper-locations: classpath*:mapper/base/*Mapper.xml,classpath*:mapper/*Mapper.xml
  typeAliasesPackage: com.redescooter.ses.service.dm.base
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #配置逻辑删除字段为1是删除
    logic-delete-value: 1
    #配置逻辑删除字段为0是未删除
    logic-not-delete-value: 0
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

# 加密秘钥
jasypt:
  encryptor:
    password: redeScooter

# 极光推送多有用配置
# value 是appid 枚举类中的值appid-systemId
jg-push: #自定义的属性和值
  listDriver:
    # vo diver 极光配置
    - name: REDE_SAAS-SAAS_APP
      appkey: 565ab684b9fee01d476a7f53
      secret: f656262e5840089252f1b37d
      apns: false
      # consumer consumer 极光配置
#  - name: SES-APP_C_DELIVERY
#    appkey: a51450edc74192b2a7b13e4e
#    secret: 674c7b2b8740f489a465c011
#    apns: false
