#Springboot 基础配置
spring:
  application:
    name: @project.artifactId@
  profiles:
    active: @profile-active@
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
    encoding: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
server:
  port: 8082
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
#DUBBO 配置
dubbo:
  application:
    id: @project.artifactId@
    name: @project.artifactId@
    #是否启动QoS
    qos-enable: false
    #是否允许远程访问
    qos-accept-foreign-ip: false
    logger: log4j
  #Dubbo服务暴露与发现消费所在的package
  scan:
    base-packages: com.redescooter.ses
  #注册中心配置
  registry:
    simplified: true
    #注册中心不存在时，是否报错
    check: false
    register: true
    subscribe: true
    dynamic: true
    group: ses
    protocol: zookeeper
    timeout: 60000
    session: 60000
  #元数据配置
  metadata-report:
    group: ses
    cycle-report: true
    timeout: 60000
  #服务提供者缺省值配置
  provider:
    dynamic: true
    deprecated: true
    timeout: 60000
    threads: 400
  #服务消费者缺省值配置
  consumer:
    #启动时检查提供者是否存在，true报错，false忽略
    check: false
    lazy: true
    timeout: 60000
    filter: dubboAccessLogFilter
    threads: 600
  protocol:
    register: true
    port: -1
    threads: 400
    name: dubbo
  reference:
    check: false
