#日志路径
log:
  file:
    path: ${log.path}@profile-active@
    max-size: 128MB
    max-history: 180

dubbo:                                                                                                                  ##DUBBO配置
  registry:                                                                                                             #注册中心
    address: zookeeper://172.31.5.73:2181?backup=172.31.5.73:2182,172.31.5.73:2183
    
# swagger配置

jasypt:
  encryptor:
    property:
      prefix: RedE(   # 加密前缀
      suffix: )            # 加密后缀
    ivGeneratorClassname: org.jasypt.salt.RandomIVGenerator

spring:
  #上传配置
  http:
  servlet:
    multipart:
      max-request-size: 1000MB
      max-file-size: 20MB
      enabled: true
  #数据库连接
  datasource:
    url: RedE(NEPCooJbmS1ZTrUV+Eljpq8oZb0nbOYHedDq/N8soNU2uVm3faUdEvMwoXe+QzuXlZMNEuyWhCHU/4F1Lh7xFNuyFr7ilPQ74x6ZAohYX8Ebb4w6IqD4u6cjVwiBsZ+ADZScYCuPU5eOJa83Cxif1jMgpq8jYefDA7x7N0J5SIGjJ5tnvDY+WL6PbH6KLAuoL2olRKlOsQoX780JZ7YFEWU15MRUE6nHK681Hwpn0k0f4UaT/7gII4AvFDZKAiSTp6YXyEX7U/jMOWGfmrDtpYmtmDrtwDXnXzB6MubHcksOJdc9HAb9NkvggxrNJXxUjmL5YiqR7NHFj/DIgCbZF09llk6fKA/sXvUcCoZFzD0=)
    username: RedE(dLdpwDnWFmnxWR+GLyKLEw==)
    password: RedE(SZPYIyOyUtIs/zBJNqY2UaCMBg5DZnZZwpAuikgZlkZC0RstZ+9loCeLqWZD9l5h)
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      # 监控页面的用户名和密码 以及页面地址
      stat-view-servlet:
        login-username: rede
        login-password: admin
        enabled: true
        url-pattern: /druid/*
  #REDIS集群配置
  redis:
    cluster:
      nodes:
        - 172.31.5.73:7000
        - 172.31.5.73:7001
        - 172.31.5.73:7002
        - 172.31.5.73:7003
        - 172.31.5.73:7004
        - 172.31.5.73:7005
  # swagger在线文档配置
  swagger:
    enabled: false  # 是否启用swagger

oss:                                                                                                                    #阿里oss上传
  #oss 使用http、https请求方式
  protocol: HTTPS


# 多注册中心配置
#    reg2:
#      group: hdg2
#      address: zookeeper://zk1.d.xqcx.com:32181?backup=zk2.d.xqcx.com:32181,zk3.d.xqcx.com:32181

